Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-08, with the labels that each got.

#463 Fix shared preview journey
  app/controllers/preview/entries_controller.rb
  app/models/task.rb
  spec/features/design/preview_step_spec.rb
  spec/requests/entry_preview_spec.rb
Labels: bug

#462 Doc for exporting CSV data from CF envs
  doc/cloud-foundry-utilities.md
Labels: documentation

#464 Fix sign out bug introduced by addition of rails_ujs
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user_session.rb
  app/services/find_or_create_user_from_session.rb
  app/views/layouts/_navigation_links.html.erb
  config/routes.rb
  spec/features/auth/sign_in_spec.rb
  spec/features/auth/sign_out_spec.rb
  spec/features/landing/body_spec.rb
  spec/requests/authentication_spec.rb
  spec/services/find_or_create_user_from_session_spec.rb
Labels: bug

#467 (Re)define "stale" and "started" state for a journey
  CHANGELOG.md
  app/jobs/delete_stale_journeys_job.rb
  app/jobs/flag_stale_journeys_job.rb
  app/models/journey.rb
  app/services/create_journey.rb
  app/services/delete_stale_journeys.rb
  app/services/flag_stale_journeys.rb
  config/schedule.yml
  db/migrate/20210805130832_change_journey_started_to_false.rb
  db/schema.rb
  spec/factories/journey.rb
  spec/fixtures/contentful/001-categories/category-peter.json
  spec/fixtures/contentful/002-sections/section-1-peter.json
  spec/fixtures/contentful/002-sections/section-2-peter.json
  spec/fixtures/contentful/002-sections/section-3-peter.json
  spec/jobs/delete_stale_journeys_job_spec.rb
  spec/jobs/flag_stale_journeys_job_spec.rb
  spec/models/journey/journey_all_tasks_completed_spec.rb
  spec/models/journey_spec.rb
  spec/services/create_journey_spec.rb
  spec/services/delete_stale_journeys_spec.rb
  spec/services/flag_stale_journeys_spec.rb
Labels: bug, enhancement

#501 Skip button navigation fix
  app/controllers/answers_controller.rb
  spec/features/self-serve/steps/presenter_spec.rb
Labels: bug
