Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-09, with the labels that each got.

#497 Add a functional base service to send emails via Notify
  .env.example
  .env.test
  Gemfile
  Gemfile.lock
  app/services/emails/confirmation.rb
  app/services/emails/document.rb
  doc/architecture/decisions/0018-use-notify-api-for-sending-emails.md
  doc/notify.md
  lib/notify/email.rb
  lib/school/mapper.rb
  spec/lib/self-serve/notify/email_spec.rb
  spec/services/self-serve/emails/confirmation_spec.rb
  spec/services/self-serve/emails/document_spec.rb
Labels: enhancement

#508 Fix task order migration bug
  db/migrate/20210730083035_add_missing_order_to_existing_tasks.rb
Labels: bug

#498 Add Cases controller, views and presenters
  app/controllers/support/cases_controller.rb
  app/models/support/case.rb
  app/presenters/support/agent_presenter.rb
  app/presenters/support/base_presenter.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/category_presenter.rb
  app/presenters/support/contact_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/_interaction.html.erb
  app/views/support/cases/_row.erb
  app/views/support/cases/_school_details.html.erb
  app/views/support/cases/index.html.erb
  app/views/support/cases/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/admin_spec.rb
  spec/features/support/case_index_spec.rb
  spec/features/support/case_show_spec.rb
  spec/presenters/support/agent_presenter_spec.rb
  spec/presenters/support/base_presenter_spec.rb
  spec/presenters/support/case_presenter_spec.rb
  spec/presenters/support/contact_presenter_spec.rb
  spec/presenters/support/interaction_presenter_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#513 Decorate Models
  app/controllers/answers_controller.rb
  app/controllers/application_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/design_controller.rb
  app/controllers/journeys_controller.rb
  app/controllers/specifications_controller.rb
  app/controllers/steps_controller.rb
  app/models/journey.rb
  app/presenters/category_presenter.rb
  app/presenters/contentful_entry_presenter.rb
  app/presenters/journey_presenter.rb
  app/views/dashboard/show.html.erb
  app/views/design/show.html.erb
  app/views/journeys/confirm_delete.html.erb
  app/views/journeys/delete.html.erb
  app/views/journeys/show.html.erb
  app/views/steps/_edit_form_wrapper.html.erb
  app/views/steps/_new_form_wrapper.html.erb
  app/views/steps/checkboxes.html.erb
  app/views/steps/currency.html.erb
  app/views/steps/long_text.html.erb
  app/views/steps/markdown.html.erb
  app/views/steps/number.html.erb
  app/views/steps/paragraphs.html.erb
  app/views/steps/radios.html.erb
  app/views/steps/short_text.html.erb
  app/views/steps/single_date.html.erb
  spec/factories/journey.rb
  spec/models/self-serve/journey_spec.rb
  spec/presenters/self-serve/contentful_entry_presenter_spec.rb
  spec/presenters/self-serve/journey_presenter_spec.rb
  spec/support/contentful_helpers.rb
Labels: refactor

#482 Support Request Journey
  CHANGELOG.md
  app/controllers/support_requests_controller.rb
  app/controllers/users_controller.rb
  app/forms/support_form_wizard.rb
  app/models/support_request.rb
  app/models/user.rb
  app/views/dashboard/show.html.erb
  app/views/support_requests/_form/_form.html.erb
  app/views/support_requests/_form/_step_1.html.erb
  app/views/support_requests/_form/_step_2.html.erb
  app/views/support_requests/_form/_step_3.html.erb
  app/views/support_requests/_form/_step_4.html.erb
  app/views/support_requests/edit.html.erb
  app/views/support_requests/index.html.erb
  app/views/support_requests/new.html.erb
  app/views/support_requests/show.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210811120013_add_contact_details_to_user.rb
  db/migrate/20210811123204_create_support_requests.rb
  db/migrate/20210909113848_add_phone_number_to_support_request.rb
  db/schema.rb
  doc/form_objects.md
  spec/factories/support_requests.rb
  spec/factories/user.rb
  spec/features/self-serve/support_requests/edit_support_request_spec.rb
  spec/features/self-serve/support_requests/new_support_request_spec.rb
  spec/features/self-serve/support_requests/show_support_request_spec.rb
  spec/form_objects/support_form_wizard_spec.rb
  spec/models/self-serve/support_request_spec.rb
  spec/models/self-serve/user_spec.rb
Labels: enhancement

#517 Fix incorrect use of `timestamps` in migration when setting new defaults
  db/migrate/20210908131247_add_default_support_category_timestamps.rb
  db/schema.rb
Labels: bug

#515 Breadcrumbs
  Gemfile
  Gemfile.lock
  app/controllers/dashboard_controller.rb
  app/controllers/journeys_controller.rb
  app/controllers/specifications_controller.rb
  app/views/layouts/_breadcrumbs.html.erb
  app/views/layouts/application.html.erb
  doc/architecture/decisions/0019-use-loaf-for-breadcrumb-links.md
  spec/features/self-serve/dashboard/existing_journey_spec.rb
  spec/features/self-serve/dashboard/new_journey_spec.rb
  spec/features/self-serve/journeys/category_spec.rb
  spec/features/self-serve/journeys/continue_spec.rb
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/journeys/view_spec.rb
Labels: enhancement

#507 Updating Category via Webhook
  CHANGELOG.md
  app/controllers/api/contentful/categories_controller.rb
  app/controllers/preview/entries_controller.rb
  app/models/category.rb
  db/migrate/20210827160410_make_contentful_id_unique_in_categories.rb
  db/migrate/20210827161206_add_timestamp_defaults_to_categories.rb
  db/migrate/20210906101533_add_missing_null_constraints_to_categories.rb
  db/schema.rb
  doc/contentful-updates.md
  spec/factories/category.rb
  spec/features/self-serve/metrics/log_update_answer_spec.rb
  spec/features/self-serve/metrics/log_view_journey_spec.rb
  spec/features/self-serve/metrics/log_view_specification_spec.rb
  spec/migrations/self-serve/add_default_to_step_tally_spec.rb
  spec/migrations/self-serve/add_missing_null_constraints_to_categories_spec.rb
  spec/migrations/self-serve/add_missing_order_to_existing_tasks_spec.rb
  spec/migrations/self-serve/add_slugs_to_existing_categories_spec.rb
  spec/migrations/self-serve/add_timestamp_defaults_to_categories_spec.rb
  spec/migrations/self-serve/associate_existing_journeys_spec.rb
  spec/migrations/self-serve/make_contentful_id_unique_in_categories_spec.rb
  spec/models/self-serve/category_spec.rb
  spec/requests/self-serve/api/contentful/webhook_upsert_category_spec.rb
Labels: enhancement

#516 Add views and actions for assigning case to worker
  app/controllers/support/cases_controller.rb
  app/models/support/agent.rb
  app/models/support/case.rb
  app/presenters/support/agent_presenter.rb
  app/presenters/support/base_presenter.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/category_presenter.rb
  app/presenters/support/contact_presenter.rb
  app/views/support/admin/show.html.erb
  app/views/support/cases/edit.html.erb
  app/views/support/cases/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210913154819_create_support_agents.rb
  db/migrate/20210913154900_add_agent_references_to_support_cases.rb
  db/schema.rb
  spec/factories/support/agent.rb
  spec/features/support/case_edit_spec.rb
  spec/features/support/case_index_spec.rb
  spec/features/support/case_show_spec.rb
  spec/models/support/agent_spec.rb
  spec/presenters/support/agent_presenter_spec.rb
  spec/presenters/support/case_presenter_spec.rb
  spec/presenters/support/contact_presenter_spec.rb
Labels: enhancement

#521 Create Support Enquiry Service
  app/models/support_request.rb
  app/services/submit_support_request.rb
  spec/factories/journey.rb
  spec/factories/section.rb
  spec/factories/support_request.rb
  spec/services/self-serve/submit_support_request_spec.rb
Labels: enhancement

#523 Create Support Case Service
  CHANGELOG.md
  app/models/support/case.rb
  app/models/support/enquiry.rb
  app/services/support/create_case.rb
  db/schema.rb
  spec/factories/support/case.rb
  spec/factories/support/enquiry.rb
  spec/services/support/create_case_spec.rb
Labels: enhancement

#531 Reflect DSI profile changes
  .env.test
  app/controllers/sessions_controller.rb
  app/services/create_user.rb
  spec/features/self-serve/auth/sign_in_spec.rb
  spec/features/self-serve/auth/sign_out_spec.rb
  spec/services/self-serve/create_user_spec.rb
  spec/support/sign_in_helpers.rb
Labels: enhancement

#530 Abstract Update Case logic into separate service
  app/controllers/support/cases_controller.rb
  app/services/support/update_case.rb
  spec/features/support/case_edit_spec.rb
  spec/services/support/update_case_spec.rb
  spec/support/matchers.rb
Labels: enhancement

#532 Add informative comment delineating class purpose
  app/models/support/agent.rb
Labels: documentation

#522 Markdown for liquid templates
  Brewfile.example
  Dockerfile
  Gemfile
  Gemfile.lock
  app/controllers/specifications_controller.rb
  app/presenters/journey_presenter.rb
  app/presenters/step_presenter.rb
  app/services/document_formatter.rb
  app/services/liquid_parser.rb
  app/services/specification_renderer.rb
  app/services/submit_support_request.rb
  app/views/specifications/show.html.erb
  config/initializers/mime_types.rb
  config/locales/en.yml
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/journeys/view_spec.rb
  spec/features/self-serve/steps/statement_spec.rb
  spec/presenters/self-serve/step_presenter_spec.rb
  spec/services/self-serve/document_formatter_spec.rb
  spec/services/self-serve/liquid_parser_spec.rb
  spec/services/self-serve/specification_renderer_spec.rb
Labels: enhancement, refactor

#537 Content updates
  app/controllers/design_controller.rb
  app/presenters/category_presenter.rb
  app/presenters/journey_presenter.rb
  app/views/categories/index.html.erb
  app/views/journeys/show.html.erb
  app/views/pages/specifying_start_page.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/categories/categories_spec.rb
  spec/features/self-serve/dashboard/access_spec.rb
  spec/features/self-serve/dashboard/new_journey_spec.rb
  spec/features/self-serve/journeys/category_spec.rb
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/landing/body_spec.rb
  spec/features/self-serve/support_requests/new_support_request_spec.rb
  spec/presenters/self-serve/category_presenter_spec.rb
  spec/presenters/self-serve/journey_presenter_spec.rb
  spec/support/contentful_helpers.rb
  spec/support/journey_helpers.rb
Labels: enhancement

#544 Fix running a subset of specs in the docker test env
  script/spec
Labels: bug

#541 Add interactions to case
  app/controllers/support/interactions_controller.rb
  app/models/support/case.rb
  app/models/support/interaction.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/enquiry_presenter.rb
  app/views/layouts/application.html.erb
  app/views/support/cases/show.html.erb
  app/views/support/interactions/forms/_contact.html.erb
  app/views/support/interactions/forms/_form.html.erb
  app/views/support/interactions/forms/_note.html.erb
  app/views/support/interactions/new.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20210917120405_create_support_interactions.rb
  db/schema.rb
  package-lock.json
  spec/factories/support/interaction.rb
  spec/features/support/case_show_spec.rb
  spec/features/support/interactions/new_interaction_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/case_presenter_spec.rb
Labels: enhancement
