Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-11, with the labels that each got.

#606 Feature/228 templated email
  CHANGELOG.md
  app/assets/stylesheets/components/supported/_email-preview.scss
  app/controllers/support/cases/emails/content_controller.rb
  app/controllers/support/cases/emails_controller.rb
  app/forms/support/case_email_content_form.rb
  app/forms/support/case_email_content_form_schema.rb
  app/views/support/cases/emails/content/show.html.erb
  app/views/support/cases/emails/templates/index.html.erb
  config/initializers/notifications.rb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  lib/notify/email.rb
  spec/factories/support/case.rb
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
  spec/support/shared/notify_email_templates.rb
Labels: enhancement

#622 Change the default presence validation message
  CHANGELOG.md
  config/locales/models/single_date_answer.en.yml
  spec/features/self-serve/steps/answer_question_spec.rb
  spec/features/self-serve/steps/skippable_step_spec.rb
Labels: enhancement

#588 Documentation onboarding gaps
  doc/docker-useful-commands.md
  doc/getting-started.md
Labels: documentation

#628 Contentful CLI Github actions
  .env.example
  .github/workflows/clone-contentful-staging-to-develop.yml
  .github/workflows/clone-contentful-to-research.yml
  .github/workflows/clone-contentful-to-staging.yml
  CHANGELOG.md
  app/services/create_step.rb
  spec/services/self-serve/create_step_spec.rb
  terraform/workspace-variables/preview_app_env.yml.example
  terraform/workspace-variables/prod_app_env.yml.example
  terraform/workspace-variables/research_app_env.yml.example
  terraform/workspace-variables/staging_app_env.yml.example
Labels: dependencies

#614 DSI uses ENV
  .env.example
  .env.test
  app/helpers/application_helper.rb
  app/services/get_dsi_url.rb
  app/services/user_session.rb
  app/views/profile/show.html.erb
  config/initializers/dotenv.rb
  config/initializers/omniauth.rb
  lib/dsi/client.rb
  lib/dsi/uri.rb
  spec/features/self-serve/auth/supported_user_spec.rb
  spec/features/self-serve/profile_spec.rb
  spec/lib/self-serve/dsi/uri_spec.rb
  spec/requests/self-serve/authentication_spec.rb
  spec/services/self-serve/get_dsi_url_spec.rb
  spec/services/self-serve/user_session_spec.rb
  terraform/workspace-variables/preview_app_env.yml.example
  terraform/workspace-variables/prod_app_env.yml.example
  terraform/workspace-variables/research_app_env.yml.example
  terraform/workspace-variables/staging_app_env.yml.example
Labels: enhancement

#633 Add value thresholds and change wording
  config/static/next_steps_catering.md
  config/static/next_steps_mfd.md
Labels: bug

#632 Add case reference to the confirmation email
  app/services/submit_support_request.rb
  spec/services/self-serve/submit_support_request_spec.rb
Labels: bug

#627 Make support request link within case history conditional
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/cases/case_history/_support_request.html.erb
  app/views/support/cases/show.html.erb
  db/migrate/20211101173214_change_interaction_json_default.rb
  db/schema.rb
  spec/features/support/case_summary_spec.rb
  spec/features/support/interactions/list_interactions_spec.rb
  spec/features/support/interactions/new_interaction_spec.rb
Labels: bug

#637 Add user feedback link (Qualtrics)
  .env.example
  .env.test
  .gitignore
  CHANGELOG.md
  Dockerfile
  app/views/specifications/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/journeys/download_spec.rb
Labels: enhancement

#615 Improve and extend GIAS persistence
  app/services/support/seed_schools.rb
  db/migrate/20211101171222_add_extra_gias_fields_to_organisations.rb
  db/migrate/20211103110826_change_open_date_to_opened_date_on_support_organisations.rb
  db/schema.rb
  lib/school/information.rb
  lib/school/mapper.rb
  lib/school/record_keeper.rb
  lib/school/schema.rb
  spec/lib/self-serve/school/record_keeper_spec.rb
  spec/lib/self-serve/school/schema_call_spec.rb
Labels: bug

#638 Consolidate URI building logic for DSI
  .env.example
  .env.test
  .gitignore
  app/helpers/application_helper.rb
  app/services/get_dsi_url.rb
  app/services/user_session.rb
  app/views/profile/show.html.erb
  app/views/sessions/no_organisation_error.html.erb
  config/initializers/dotenv.rb
  config/initializers/omniauth.rb
  lib/dsi/client.rb
  lib/dsi/uri.rb
  spec/features/self-serve/auth/supported_user_spec.rb
  spec/features/self-serve/profile_spec.rb
  spec/lib/self-serve/dsi/uri_spec.rb
  spec/requests/self-serve/authentication_spec.rb
  spec/services/self-serve/get_dsi_url_spec.rb
  spec/services/self-serve/user_session_spec.rb
  terraform/workspace-variables/preview_app_env.yml.example
  terraform/workspace-variables/prod_app_env.yml.example
  terraform/workspace-variables/research_app_env.yml.example
  terraform/workspace-variables/staging_app_env.yml.example
Labels: enhancement

#644 Missing breadcrumbs on the /next-steps page
  app/controllers/pages_controller.rb
  spec/features/self-serve/pages/next_steps_catering_spec.rb
  spec/features/self-serve/pages/next_steps_mfd_spec.rb
Labels: bug

#643 Enabled skipped specs
  spec/features/support/case_summary_spec.rb
  spec/presenters/support/case_presenter_spec.rb
Labels: refactor

#654 Correct yard syntax for dry-initialiser classes
  app/forms/support/case_assignment_form.rb
  app/forms/support/case_categorisation_form.rb
  app/forms/support/case_email_content_form.rb
  app/forms/support/case_email_type_form.rb
  app/forms/support/case_resolution_form.rb
  app/forms/support/concerns/validatable_form.rb
  app/forms/support_form.rb
  app/services/create_user.rb
  app/services/current_user.rb
  app/services/document_formatter.rb
  app/services/downloader.rb
  app/services/emails/document.rb
  app/services/exporter.rb
  app/services/liquid_parser.rb
  app/services/specification_renderer.rb
  app/services/submit_support_request.rb
  app/services/support/seed_categories.rb
  app/services/support/seed_groups.rb
  app/services/support/seed_schools.rb
  lib/dsi/client.rb
  lib/dsi/user.rb
  lib/notify/email.rb
  lib/school/information.rb
Labels: documentation

#649 Test by disabling the suspected culprit
  spec/features/self-serve/support_requests/create_support_request_spec.rb
Labels: bug, help wanted, invalid

#642 Refactor docker and compose tooling
  .dockerignore
  .env.example
  .env.test
  .github/workflows/continuous-integration.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  config/initializers/dotenv.rb
  doc/getting-started.md
  docker-compose.ci.yml
  docker-compose.dev.yml
  docker-compose.test.yml
  docker-compose.yml
  docker-entrypoint.sh
  lib/tasks/yard.rake
  script/build
  script/console
  script/destroy-volume
  script/server
  script/spec
Labels: bug, refactor

#664 Page services
  app/services/content/page/build.rb
  app/services/content/page/get.rb
  spec/services/self-serve/content/page/build_spec.rb
  spec/services/self-serve/content/page/get_spec.rb
Labels: enhancement

#593 Replace fixtures with factory
  app/models/journey.rb
  db/schema.rb
  spec/features/self-serve/journeys/continue_spec.rb
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/journeys/task_list/view_answered_spec.rb
  spec/features/self-serve/journeys/task_list/view_hidden_spec.rb
  spec/features/self-serve/journeys/task_list/view_steps_spec.rb
  spec/features/self-serve/metrics/log_view_task_spec.rb
  spec/features/self-serve/steps/blank_field_spec.rb
  spec/features/self-serve/steps/presenter_spec.rb
Labels: refactor

#660 Sending case management emails
  .rubocop_todo.yml
  CHANGELOG.md
  app/controllers/support/cases/emails/content_controller.rb
  app/controllers/support/cases/emails_controller.rb
  app/forms/support/case_email_content_form.rb
  app/forms/support/case_email_content_form_schema.rb
  app/services/submit_support_request.rb
  app/services/support/emails/to_school.rb
  app/views/support/cases/emails/content/show.html.erb
  app/views/support/cases/emails/templates/index.html.erb
  config/locales/en.yml
  lib/notify/email.rb
  spec/features/self-serve/support_requests/submit_support_request_spec.rb
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
  spec/lib/self-serve/notify/email_spec.rb
  spec/services/self-serve/emails/document_spec.rb
  spec/support/shared/notify_email_templates.rb
Labels: enhancement

#670 Update webhook documentation
  doc/webhooks.md
Labels: documentation

#678 Rename service in readme
  README.md
Labels: documentation

#681 Add breadcrumbs to Pages
  app/controllers/pages_controller.rb
  app/services/content/page/build.rb
  db/migrate/20211123110903_add_breadcrumbs_to_pages.rb
  db/schema.rb
  spec/factories/pages.rb
  spec/features/pages/breadcrumbs_spec.rb
  spec/requests/self-serve/api/contentful/pages_controller_spec.rb
  spec/services/self-serve/content/page/build_spec.rb
  spec/services/self-serve/content/page/get_spec.rb
  spec/support/contentful_helpers.rb
Labels: enhancement

#631 Hub Transition Case
  .gitignore
  app/assets/javascripts/components/autocomplete/autocomplete.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/components/supported/_new-case-form.scss
  app/controllers/support/cases_controller.rb
  app/controllers/support/migrations/base_controller.rb
  app/controllers/support/migrations/hub_cases_controller.rb
  app/controllers/support/migrations/previews_controller.rb
  app/forms/support/case_hub_migration_form.rb
  app/forms/support/case_hub_migration_form_schema.rb
  app/models/support/case.rb
  app/models/support/category.rb
  app/models/support/hub_transition.rb
  app/models/support/interaction.rb
  app/models/support/organisation.rb
  app/presenters/support/case_hub_migration_form_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/services/support/create_case.rb
  app/views/components/_autocomplete.html.erb
  app/views/support/cases/index.html.erb
  app/views/support/migrations/hub_cases/forms/_case_form.html.erb
  app/views/support/migrations/hub_cases/new.html.erb
  app/views/support/migrations/previews/new.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  db/migrate/20211103134136_create_support_hub_transitions.rb
  db/migrate/20211104075345_add_source_to_case.rb
  db/migrate/20211123151744_add_org_to_support_case.rb
  db/schema.rb
  spec/factories/support/category.rb
  spec/factories/support/hub_transitions.rb
  spec/factories/support/interaction.rb
  spec/features/support/case_migration_spec.rb
  spec/forms/support/case_hub_migration_form_spec.rb
  spec/models/support/case_spec.rb
  spec/models/support/category_spec.rb
  spec/models/support/hub_transition_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/case_hub_migration_form_presenter_spec.rb
  spec/presenters/support/interaction_presenter_spec.rb
  spec/services/support/create_case_spec.rb
  spec/support/matchers.rb
Labels: enhancement

#667 [28] Dynamic Pages
  .env.test
  .rubocop_todo.yml
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  app/controllers/api/contentful/base_controller.rb
  app/controllers/api/contentful/pages_controller.rb
  app/controllers/pages_controller.rb
  app/presenters/base_presenter.rb
  app/presenters/page_presenter.rb
  app/services/content/page/build.rb
  app/services/content/page/get.rb
  app/views/pages/_sidebar.html.erb
  app/views/pages/accessibility.html.erb
  app/views/pages/next_steps_catering.html.erb
  app/views/pages/next_steps_mfd.html.erb
  app/views/pages/privacy_notice.html.erb
  app/views/pages/show.html.erb
  app/views/pages/specifying_start_page.html.erb
  app/views/pages/terms_and_conditions.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20211117133254_add_contentful_fields_to_page.rb
  db/migrate/20211118115424_change_pages_slug_to_unique.rb
  db/migrate/20211123110903_add_breadcrumbs_to_pages.rb
  db/migrate/20211129120610_update_slugs_and_contentful_ids_in_pages.rb
  db/schema.rb
  doc/architecture/decisions/0020-use-contentful-for-page-content.md
  spec/factories/pages.rb
  spec/features/pages/breadcrumbs_spec.rb
  spec/features/self-serve/pages/accessibility_spec.rb
  spec/features/self-serve/pages/next_steps_catering_spec.rb
  spec/features/self-serve/pages/next_steps_mfd_spec.rb
  spec/features/self-serve/pages/privacy_spec.rb
  spec/features/self-serve/pages/show_spec.rb
  spec/features/self-serve/pages/terms_and_conditions_spec.rb
  spec/migrations/self-serve/update_slugs_and_contentful_ids_in_pages_spec.rb
  spec/models/page_spec.rb
  spec/requests/self-serve/api/contentful/pages_controller_spec.rb
  spec/services/self-serve/content/page/build_spec.rb
  spec/services/self-serve/content/page/get_spec.rb
  spec/support/contentful_helpers.rb
Labels: enhancement

#686 Add invitation to reuse code to the README
  README.md
Labels: documentation

#680 Unsupported scope
  app/models/user.rb
  spec/models/self-serve/user/user_internal_spec.rb
  spec/models/self-serve/user/user_supported_spec.rb
  spec/models/self-serve/user/user_unsupported_spec.rb
Labels: enhancement

#682 When existing users change orgs
  app/services/create_user.rb
  spec/services/self-serve/create_user_spec.rb
Labels: enhancement

#690 Change open status to opened on Support::Case
  app/controllers/support/cases/assignments_controller.rb
  app/models/support/case.rb
  app/views/support/cases/show.html.erb
  config/locales/en.yml
  spec/features/support/case_assignment_spec.rb
  spec/features/support/case_resolution_spec.rb
  spec/features/support/case_school_details_spec.rb
  spec/features/support/case_summary_spec.rb
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
  spec/features/support/interactions/list_interactions_spec.rb
  spec/features/support/interactions/new_interaction_spec.rb
  spec/models/support/case_spec.rb
Labels: bug

#687 Feature/98 display email body in new tab
  app/controllers/support/interactions_controller.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/_interaction.html.erb
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/interactions/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/interactions/list_interactions_spec.rb
Labels: enhancement

#685 ADR for accessable autocomplete
  doc/architecture/decisions/0020-use-accessible-autocomplete-for-autocomplete-fields.md
Labels: documentation
