Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-12, with the labels that each got.

#691 Updated support request additional data (interaction) styling
  app/presenters/support/case_presenter.rb
  app/services/submit_support_request.rb
  app/views/support/cases/case_history/_support_request.html.erb
  config/locales/en.yml
  spec/features/self-serve/pages/show_spec.rb
  spec/features/self-serve/support_requests/submit_support_request_spec.rb
  spec/presenters/support/case_presenter_spec.rb
  spec/services/self-serve/submit_support_request_spec.rb
Labels: bug

#651 Yard for improved documentation
  .yardopts
  README.md
  lib/tasks/yard.rake
Labels: documentation

#697 Procurement data model
  app/models/support/case.rb
  app/models/support/procurement.rb
  db/migrate/20211202151356_create_support_procurements.rb
  db/migrate/20211202153336_add_procurement_to_case.rb
  db/schema.rb
  spec/factories/support/procurement.rb
  spec/models/support/case_spec.rb
  spec/models/support/procurement_spec.rb
Labels: enhancement

#699 Bug fix
  app/services/submit_support_request.rb
  app/services/support/create_case.rb
  spec/services/self-serve/submit_support_request_spec.rb
Labels: bug

#705 Tidy CHANGELOG for release
  CHANGELOG.case_management.md
  CHANGELOG.md
  doc/architecture/decisions/0020-use-accessible-autocomplete-for-autocomplete-fields.md
Labels: documentation

#701 Ensure agent cant be nil
  app/controllers/support/application_controller.rb
  app/controllers/support/cases/application_controller.rb
  app/controllers/support/cases_controller.rb
  spec/features/support/interactions/list_interactions_spec.rb
  spec/requests/support/authorisation_spec.rb
  spec/requests/support/schools_spec.rb
  spec/support/sign_in_helpers.rb
Labels: bug

#702 Attachments incoming email
  .rubocop_todo.yml
  Gemfile.lock
  lib/microsoft_graph/microsoft_graph.rb
  lib/microsoft_graph/resource/attachment.rb
  spec/lib/microsoft_graph/resource/attachment_spec.rb
Labels: enhancement

#708 Uploaded email link and spec
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/cases/show.html.erb
  spec/features/self-serve/pages/show_spec.rb
  spec/features/support/interactions/list_interactions_spec.rb
Labels: bug

#707 Last-minute procurement entity creation
  app/services/support/create_case.rb
  app/views/support/cases/show.html.erb
  lib/tasks/case_management.rake
  spec/services/support/create_case_spec.rb
Labels: enhancement

#706 Update contract form
  app/controllers/support/cases/contracts_controller.rb
  app/controllers/support/cases/procurement_details_controller.rb
  app/forms/support/case_contracts_form.rb
  app/forms/support/case_contracts_form_schema.rb
  app/forms/support/case_hub_migration_form_schema.rb
  app/forms/support/case_procurement_details_form.rb
  app/forms/support/case_procurement_details_form_schema.rb
  app/forms/support/form.rb
  app/forms/support/schema.rb
  app/models/support/contract.rb
  app/presenters/support/base_presenter.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/contract_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/presenters/support/procurement_presenter.rb
  app/views/support/cases/_procurement_details.html.erb
  app/views/support/cases/existing_contracts/edit.html.erb
  app/views/support/cases/new_contracts/edit.html.erb
  app/views/support/cases/procurement_details/edit.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  db/schema.rb
  spec/factories/contracts.rb
  spec/factories/support/case.rb
  spec/factories/support/existing_contract.rb
  spec/factories/support/new_contract.rb
  spec/features/support/procurement_details/edit_existing_contract_spec.rb
  spec/features/support/procurement_details/edit_new_contract_spec.rb
  spec/features/support/procurement_details/edit_procurment_details_spec.rb
  spec/features/support/procurement_details/edit_savings_spec.rb
  spec/forms/support/case_contracts_form_spec.rb
  spec/forms/support/case_procurement_details_form_spec.rb
  spec/models/support/case_spec.rb
  spec/presenters/support/base_presenter_spec.rb
Labels: enhancement

#718 Log when steps are skipped
  app/controllers/steps_controller.rb
  app/services/record_action.rb
  spec/features/self-serve/metrics/log_skip_step_spec.rb
  spec/services/self-serve/record_action_spec.rb
Labels: enhancement

#729 Internal admin page secured by check on user roles
  app/controllers/admin_controller.rb
  app/models/user.rb
  app/presenters/user_presenter.rb
  app/views/admin/show.html.erb
  app/views/errors/missing_role.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/factories/user.rb
  spec/features/self-serve/admin/show_spec.rb
  spec/models/self-serve/user/user_analyst_spec.rb
Labels: enhancement

#730 Data download link
  app/controllers/admin_controller.rb
  app/views/admin/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/admin/show_spec.rb
Labels: enhancement
