Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-10, with the labels that each got.

#538 Create restricted entry point for case management agents
  .env.example
  .env.test
  app/controllers/pages_controller.rb
  app/controllers/support/admin_controller.rb
  app/controllers/support/agents_controller.rb
  app/controllers/support/application_controller.rb
  app/controllers/support/pages_controller.rb
  app/models/guest.rb
  app/models/support/agent.rb
  app/presenters/buyer_presenter.rb
  app/presenters/support/agent_presenter.rb
  app/presenters/support/base_presenter.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/category_presenter.rb
  app/services/create_user.rb
  app/views/pages/specifying_start_page.html.erb
  app/views/support/admin/show.html.erb
  app/views/support/cases/_interaction.html.erb
  app/views/support/pages/start_page.html.erb
  config/initializers/_dotenv.rb
  config/initializers/omniauth.rb
  config/routes.rb
  db/migrate/20210921114706_add_auth_to_support_agents.rb
  db/migrate/20210921115522_add_email_to_support_agents.rb
  db/schema.rb
  spec/factories/support/agent.rb
  spec/features/support/admin_spec.rb
  spec/features/support/case_agent_spec.rb
  spec/features/support/case_edit_spec.rb
  spec/features/support/case_list_spec.rb
  spec/features/support/case_summary_spec.rb
  spec/features/support/case_worker_login_spec.rb
  spec/features/support/interactions/new_interaction_spec.rb
  spec/models/self-serve/guest_spec.rb
  spec/models/support/agent_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/base_presenter_spec.rb
  spec/presenters/support/case_presenter_spec.rb
  spec/services/self-serve/create_user_spec.rb
  spec/support/shared/support_agent.rb
Labels: enhancement

#552 Revised support request form with new validations and email confirmation
  CHANGELOG.md
  Gemfile
  Gemfile.lock
  app/controllers/api/support/requests_controller.rb
  app/controllers/categories_controller.rb
  app/controllers/profile_controller.rb
  app/controllers/support_requests_controller.rb
  app/controllers/users_controller.rb
  app/forms/support_form.rb
  app/forms/support_form_schema.rb
  app/forms/support_form_wizard.rb
  app/models/category.rb
  app/models/support.rb
  app/models/support_request.rb
  app/models/user.rb
  app/presenters/journey_presenter.rb
  app/presenters/user_presenter.rb
  app/services/create_user.rb
  app/services/submit_support_request.rb
  app/views/dashboard/show.html.erb
  app/views/journeys/show.html.erb
  app/views/profile/show.html.erb
  app/views/support_requests/_form/_form.html.erb
  app/views/support_requests/_form/_step_1.html.erb
  app/views/support_requests/_form/_step_2.html.erb
  app/views/support_requests/_form/_step_3.html.erb
  app/views/support_requests/_form/_step_4.html.erb
  app/views/support_requests/edit.html.erb
  app/views/support_requests/index.html.erb
  app/views/support_requests/new.html.erb
  app/views/support_requests/show.html.erb
  app/views/users/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20210729145738_associate_existing_journeys.rb
  db/migrate/20210918135201_support_form_refactor.rb
  db/migrate/20210922175530_add_submitted_to_support_requests.rb
  db/schema.rb
  doc/forms.md
  docker-compose.yml
  spec/factories/support_request.rb
  spec/features/self-serve/dashboard/dashboard_spec.rb
  spec/features/self-serve/journeys/task_list/view_steps_spec.rb
  spec/features/self-serve/profile_spec.rb
  spec/features/self-serve/support_requests/create_support_request_spec.rb
  spec/features/self-serve/support_requests/edit_support_request_spec.rb
  spec/features/self-serve/support_requests/new_support_request_spec.rb
  spec/features/self-serve/support_requests/show_support_request_spec.rb
  spec/features/self-serve/support_requests/submit_support_request_spec.rb
  spec/form_objects/support_form_wizard_spec.rb
  spec/forms/self-serve/support_form_spec.rb
  spec/models/self-serve/support_request_spec.rb
  spec/services/self-serve/create_user_spec.rb
  spec/services/self-serve/submit_support_request_spec.rb
Labels: bug, enhancement, refactor

#547 Fix specification appearance
  app/assets/stylesheets/components/_specification.scss
  app/presenters/long_text_answer_presenter.rb
  app/services/document_formatter.rb
  app/views/pages/planning_start_page.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/journeys/category_spec.rb
  spec/features/self-serve/landing/body_spec.rb
  spec/features/self-serve/planning/start_page_spec.rb
  spec/features/self-serve/steps/presenter_spec.rb
  spec/presenters/self-serve/long_text_answer_presenter_spec.rb
  spec/services/self-serve/document_formatter_spec.rb
  spec/services/self-serve/get_answers_for_steps_spec.rb
Labels: bug

#553 Error pages not working
  config/application.rb
  spec/features/self-serve/errors/custom_errors_spec.rb
  spec/requests/self-serve/errors_spec.rb
Labels: bug

#617 Fix footer content and markdown pages
  app/controllers/pages_controller.rb
  app/helpers/application_helper.rb
  app/views/layouts/application.html.erb
  app/views/pages/accessibility.html.erb
  app/views/pages/planning_start_page.html.erb
  app/views/pages/privacy_notice.html.erb
  app/views/pages/terms_and_conditions.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  config/static/accessibility.md
  config/static/next_steps_catering.md
  config/static/next_steps_mfd.md
  config/static/privacy_notice.md
  config/static/terms_and_conditions.md
  lib/tasks/static_pages.rake
  spec/features/common/static_pages/accessibility_spec.rb
  spec/features/common/static_pages/privacy_spec.rb
  spec/features/common/static_pages/terms_and_conditions_spec.rb
  spec/features/self-serve/layout_spec.rb
  spec/features/self-serve/pages/accessibility_spec.rb
  spec/features/self-serve/pages/next_steps_catering_spec.rb
  spec/features/self-serve/pages/next_steps_mfd_spec.rb
  spec/features/self-serve/pages/privacy_spec.rb
  spec/features/self-serve/pages/terms_and_conditions_spec.rb
  spec/features/self-serve/planning/start_page_spec.rb
  spec/helpers/self-serve/application_helper_spec.rb
  spec/requests/self-serve/authentication_spec.rb
Labels: bug
