Repository DFE-Digital/buy-for-your-school, pull requests merged in 2021-07, with the labels that each got.

#430 Comment out CC Test Reporter & removed badge
  README.md
  script/test
Labels: bug

#435 #216: Multi-category support Contentful Entry Map page
  CHANGELOG.md
  app/controllers/journey_maps_controller.rb
  app/services/contentful_connector.rb
  app/services/get_all_contentful_entries.rb
  app/views/journey_maps/index.html.erb
  app/views/journey_maps/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/journey_mapping/journey_map_spec.rb
  spec/requests/authentication_spec.rb
  spec/services/contentful_connector_spec.rb
  spec/services/get_all_contentful_entries_spec.rb
Labels: enhancement

#428 #190: Select Category for New Specification
  CHANGELOG.md
  app/controllers/categories_controller.rb
  app/controllers/journeys_controller.rb
  app/views/categories/index.html.erb
  app/views/dashboard/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/categories/categories_spec.rb
  spec/features/dashboard/dashboard_spec.rb
  spec/features/school_buying_professionals/complete_a_journey_spec.rb
  spec/features/school_buying_professionals/view_a_list_of_tasks_spec.rb
  spec/features/visitors/anyone_can_sign_in_with_dfe_sign_in_spec.rb
  spec/rails_helper.rb
  spec/requests/authentication_spec.rb
  spec/requests/contentful_caching_spec.rb
  spec/support/journey_helpers.rb
  spec/support/sign_in_helpers.rb
Labels: enhancement

#446 Permit designers to preview entries in the staging environment
  app/controllers/preview/entries_controller.rb
  spec/features/journey_mapping/preview_step_spec.rb
  spec/helpers/application_helper_spec.rb
  spec/requests/entry_preview_spec.rb
Labels: bug, enhancement

#444 allow user to delete spec from dashboard
  CHANGELOG.md
  app/assets/javascripts/application.js
  app/controllers/dashboard_controller.rb
  app/controllers/journeys_controller.rb
  app/views/dashboard/show.html.erb
  app/views/journeys/confirm_delete.html.erb
  app/views/journeys/delete.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  config/routes.rb
  package-lock.json
  package.json
  spec/features/dashboard/delete_journey_spec.rb
Labels: enhancement

#440 User-friendly URLs for journey maps
  CHANGELOG.md
  app/controllers/design_controller.rb
  app/services/contentful_connector.rb
  app/views/design/index.html.erb
  app/views/design/show.html.erb
  app/views/journey_maps/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/design/design_spec.rb
  spec/features/design/preview_step_spec.rb
  spec/features/design/show_spec.rb
  spec/features/journey_mapping/journey_map_spec.rb
  spec/fixtures/contentful/001-categories/category-with-dynamic-liquid-template.json
  spec/fixtures/contentful/001-categories/category-with-invalid-liquid-template.json
  spec/fixtures/contentful/001-categories/category-with-liquid-template.json
  spec/fixtures/contentful/001-categories/category-with-no-steps.json
  spec/fixtures/contentful/001-categories/category-with-no-title.json
  spec/fixtures/contentful/001-categories/checkboxes-question.json
  spec/fixtures/contentful/001-categories/currency-question.json
  spec/fixtures/contentful/001-categories/extended-checkboxes-question.json
  spec/fixtures/contentful/001-categories/extended-long-answer-checkboxes-question.json
  spec/fixtures/contentful/001-categories/extended-long-answer-radio-question.json
  spec/fixtures/contentful/001-categories/extended-radio-question.json
  spec/fixtures/contentful/001-categories/hidden-field.json
  spec/fixtures/contentful/001-categories/journey-with-multiple-entries.json
  spec/fixtures/contentful/001-categories/journey-with-repeat-entries.json
  spec/fixtures/contentful/001-categories/long-text-question.json
  spec/fixtures/contentful/001-categories/markdown-help-text.json
  spec/fixtures/contentful/001-categories/mfd-radio-question.json
  spec/fixtures/contentful/001-categories/missing-entry-id.json
  spec/fixtures/contentful/001-categories/multiple-sections-and-steps.json
  spec/fixtures/contentful/001-categories/multiple-sections.json
  spec/fixtures/contentful/001-categories/multiple-specification-templates.json
  spec/fixtures/contentful/001-categories/nil-help-text-radios.json
  spec/fixtures/contentful/001-categories/nil-help-text-short-text.json
  spec/fixtures/contentful/001-categories/number-question.json
  spec/fixtures/contentful/001-categories/radio-question-with-separator.json
  spec/fixtures/contentful/001-categories/radio-question.json
  spec/fixtures/contentful/001-categories/section-with-multiple-tasks.json
  spec/fixtures/contentful/001-categories/section-with-single-hidden-task.json
  spec/fixtures/contentful/001-categories/section-with-single-task.json
  spec/fixtures/contentful/001-categories/section-with-visible-and-hidden-tasks.json
  spec/fixtures/contentful/001-categories/short-text-question.json
  spec/fixtures/contentful/001-categories/show-one-additional-question-in-order.json
  spec/fixtures/contentful/001-categories/show-one-additional-question.json
  spec/fixtures/contentful/001-categories/single-date-question.json
  spec/fixtures/contentful/001-categories/skippable-checkboxes-question.json
  spec/fixtures/contentful/001-categories/statement.json
  spec/fixtures/contentful/001-categories/task-with-multiple-steps.json
  spec/fixtures/contentful/001-categories/unexpected-contentful-question-type.json
  spec/fixtures/contentful/001-categories/unexpected-contentful-type.json
  spec/requests/authentication_spec.rb
  spec/support/contentful_helpers.rb
Labels: enhancement

#387 Implement dynamic validation defined in Contentful
  CHANGELOG.md
  app/models/currency_answer.rb
  app/models/number_answer.rb
  app/models/single_date_answer.rb
  app/services/create_step.rb
  app/validators/range_validator.rb
  db/migrate/20210721115748_add_validation_criteria_to_steps.rb
  db/schema.rb
  spec/factories/step.rb
  spec/features/landing/body_spec.rb
  spec/features/steps/answer_validation_spec.rb
  spec/fixtures/contentful/002-sections/single-date-section.json
  spec/fixtures/contentful/003-tasks/single-date-validation-task.json
  spec/fixtures/contentful/004-steps/single-date-in-past-question.json
  spec/models/currency_answer_spec.rb
  spec/models/single_date_answer_spec.rb
  spec/models/step_spec.rb
  spec/services/create_step_spec.rb
  spec/support/contentful_helpers.rb
Labels: enhancement

#456 Clear the session data on a failed authentication and redirect
  app/controllers/sessions_controller.rb
  spec/features/landing/dfe_sign_in_spec.rb
  spec/requests/authentication_spec.rb
Labels: enhancement
