Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-09, with the labels that each got.

#1104 Create a new email thread
  app/assets/stylesheets/components/supported/_messages.scss
  app/controllers/support/cases/message_threads_controller.rb
  app/controllers/support/cases/messages_controller.rb
  app/forms/support/messages/reply_form.rb
  app/forms/support/messages/reply_form_schema.rb
  app/javascript/application.js
  app/javascript/components/add-recipients.js
  app/javascript/components/display-cc-bcc.js
  app/services/support/messages/outlook/message.rb
  app/services/support/messages/outlook/send_new_message.rb
  app/views/support/cases/message_threads/index.html.erb
  app/views/support/cases/message_threads/new.html.erb
  app/views/support/cases/messages/replies/_form.html.erb
  app/views/support/cases/messages/replies/_new_message_components.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  lib/array_builder.rb
  lib/microsoft_graph/client.rb
  lib/microsoft_graph/resource/message.rb
  lib/microsoft_graph/resource/recipient.rb
  lib/microsoft_graph/transformer/message.rb
  lib/microsoft_graph/transformer/update_message.rb
  lib/types.rb
  spec/features/support/emails/agent_can_send_new_emails_spec.rb
  spec/forms/support/messages/reply_form_schema_spec.rb
  spec/forms/support/messages/reply_form_spec.rb
  spec/lib/array_builder_spec.rb
  spec/lib/microsoft_graph/client_spec.rb
  spec/services/support/messages/outlook/message_spec.rb
  spec/services/support/messages/outlook/send_new_message_spec.rb
Labels: enhancement, qa-seeded, qa-6, qa-deployed

#1132 Updated gems and yarn
  Gemfile.lock
  yarn.lock
Labels: qa-skip

#1137 PWM666 - Allow viewing of quoted reply
  app/presenters/support/messages/outlook_message_presenter.rb
  spec/presenters/support/messages/outlook_message_presenter_spec.rb
Labels: qa-seeded, qa-deployed, qa-5

#1142 Always show message recap
  app/presenters/support/messages/notify_message_presenter.rb
  app/presenters/support/messages/outlook_message_presenter.rb
  app/views/support/cases/message_threads/_four_or_less_messages.html.erb
  app/views/support/cases/message_threads/_greater_than_four_messages.html.erb
  app/views/support/cases/message_threads/_message.erb
Labels: qa-skip

#1138 Unread messages are in bold in thread view of CMS
  Gemfile.lock
  app/assets/stylesheets/components/supported/_messages.scss
  app/presenters/support/message_thread_presenter.rb
  app/views/support/cases/message_threads/_logged_contact_thread.html.erb
  app/views/support/cases/message_threads/_templated_message_thread.html.erb
  app/views/support/cases/message_threads/_thread.html.erb
  spec/factories/support/email.rb
  spec/features/support/emails/agent_sees_email_threads_spec.rb
  yarn.lock
Labels: enhancement, in-qa-env, qa-seeded, qa-deployed, qa-5

#1134 Dev: Case statistics page - add dashboard (first iteration)
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/components/supported/_case-statistics.scss
  app/controllers/support/case_statistics_controller.rb
  app/controllers/support/towers_controller.rb
  app/models/support/tower.rb
  app/views/support/case_statistics/show.html.erb
  app/views/support/towers/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220830135926_create_support_towers.rb
  db/schema.rb
  db/views/support_towers_v01.sql
  spec/features/support/case_statistics_spec.rb
  spec/features/support/towers_spec.rb
Labels: enhancement, in-qa-env, qa-seeded, qa-deployed, qa-1

#1145 Updated knapsack
  knapsack_rspec_report.json
Labels: qa-skip

#1163 Update gems 280922
  .gitignore
  Gemfile.lock
  yarn.lock
Labels: qa-seeded, qa-deployed, qa-1

#1164 TO field pre-populated on new message thread page
  app/assets/stylesheets/components/supported/_messages.scss
  app/controllers/support/cases/message_threads_controller.rb
  app/javascript/components/add-recipients.js
  app/views/support/cases/messages/replies/_form.html.erb
  app/views/support/cases/messages/replies/_new_message_components.html.erb
  config/locales/en.yml
  spec/features/support/emails/agent_can_send_new_emails_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1165 Updates to the procurement amount page
  app/controllers/framework_requests_controller.rb
  app/controllers/support_requests_controller.rb
  app/forms/framework_support_form.rb
  app/forms/request_form.rb
  app/forms/request_form_schema.rb
  app/forms/support_form.rb
  app/javascript/request/procurement_amount.js
  app/presenters/request_presenter.rb
  app/views/requests/_form/_confidence_level.html.erb
  app/views/requests/_form/_procurement_amount.html.erb
  app/views/requests/_form/_special_requirements.html.erb
  config/i18n-tasks.yml
  config/locales/en.yml
  config/locales/validation/en.yml
  db/migrate/20220928135119_remove_about_procurement_from_requests.rb
  db/schema.rb
  spec/factories/framework_requests.rb
  spec/factories/support_request.rb
  spec/features/self-serve/framework_requests/create_framework_request_dsi_spec.rb
  spec/features/self-serve/framework_requests/create_framework_request_guest_spec.rb
  spec/features/self-serve/support_requests/create_support_request_spec.rb
  spec/features/self-serve/support_requests/edit_support_request_spec.rb
  spec/forms/self-serve/request_form_schema_spec.rb
  spec/forms/self-serve/request_form_spec.rb
  spec/presenters/self-serve/request_presenter_spec.rb
Labels: enhancement, qa-seeded, qa-deployed, qa-2
