Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-05, with the labels that each got.

#985 Add reply form to a message
  app/controllers/support/cases/messages_controller.rb
  app/controllers/support/cases_controller.rb
  app/forms/support/messages/reply_form.rb
  app/forms/support/messages/reply_form_schema.rb
  app/services/support/messages/send.rb
  app/views/support/cases/emails/_read_badge.html.erb
  app/views/support/cases/messages/_actions.html.erb
  app/views/support/cases/messages/_outlook_message.html.erb
  app/views/support/cases/messages/_reply_form.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  spec/features/support/case_attachments/agent_can_save_attachments_to_case_spec.rb
  spec/features/support/emails/agent_can_mark_email_as_read_spec.rb
  spec/features/support/emails/agent_can_send_replies_spec.rb
  spec/forms/support/messages/reply_form_schema_spec.rb
  spec/services/support/messages/send_spec.rb
Labels: enhancement, in-qa-env

#987 Preview email
  app/controllers/support/cases/messages/reply_controller.rb
  app/services/support/messages/send.rb
  app/services/support/messages/templates.rb
  app/views/support/cases/messages/_outlook_message.html.erb
  app/views/support/cases/messages/_reply_form.html.erb
  app/views/support/cases/messages/reply/edit.html.erb
  app/views/support/cases/messages/reply/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/emails/agent_can_preview_email_spec.rb
  spec/features/support/emails/agent_can_send_replies_spec.rb
  spec/services/support/messages/templates_spec.rb
Labels: enhancement, in-qa-env

#995 Remove the default wording from the non template email
  app/controllers/support/cases/emails/content_controller.rb
  app/forms/support/case_email_content_form.rb
  config/locales/en.yml
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
Labels: enhancement, in-qa-env, Ready To Merge

#992 886 and 887 - Add referrer, case support level, and case value to case statistics csv
  app/models/support/case_datum.rb
  db/migrate/20220510130621_update_support_case_data_to_version_5.rb
  db/schema.rb
  db/views/support_case_data_v05.sql
  spec/models/support/case_datum_spec.rb
Labels: enhancement, in-qa-env, Ready To Merge

#991 Parsing of the spend value in contracts form
  app/forms/support/case_contracts_form.rb
  app/forms/support/case_contracts_form_schema.rb
  config/locales/validation/support/en.yml
  lib/decimal_builder.rb
  lib/types.rb
  spec/forms/support/case_contracts_form_schema_spec.rb
  spec/lib/decimal_builder_spec.rb
Labels: bug, in-qa-env, Ready To Merge

#994 Be able to send out UR survey via CM when the case is in Resolved status
  app/views/support/cases/_case_actions.html.erb
Labels: enhancement, in-qa-env

#998 Display email on case search for cases without organisation name
  app/controllers/support/cases/searches_controller.rb
  app/presenters/support/case_search_presenter.rb
  db/migrate/20220517093315_update_support_case_searches_to_version_3.rb
  db/schema.rb
  db/views/support_case_searches_v03.sql
Labels: bug, in-qa-env
