Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-08, with the labels that each got.

#1072 Update gems and node packages
  Gemfile.lock
  package.json
  yarn.lock
Labels: ruby, javascript

#1067 PWNN-364 Missing HTTP Security Headers
  config/environments/production.rb
Labels: enhancement, in-qa-env

#1070 PWNN-362 Open Redirection
  app/controllers/application_controller.rb
  app/controllers/support/cases_controller.rb
  app/views/support/cases/searches/_result.html.erb
Labels: enhancement, in-qa-env

#1064 Pwnn 391 update the order by which cases are sorted
  app/controllers/support/cases_controller.rb
  app/jobs/support/send_exit_survey_job.rb
  app/models/support/case.rb
  spec/models/support/case_spec.rb
Labels: in-qa-env

#1063 PWNN-336/334 Search by case reference without leading zeros
  app/forms/support/case_filter_form.rb
  app/forms/support/case_search_form_schema.rb
  app/models/support/agent.rb
  app/models/support/case_search.rb
  config/locales/validation/support/en.yml
  spec/features/support/search_cases_spec.rb
  spec/models/support/case_search_spec.rb
Labels: in-qa-env

#1080 Update Rails and other dependencies
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/task.rb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_7_0.rb
  config/initializers/permissions_policy.rb
  db/migrate/20220801144005_remove_not_null_on_active_storage_blobs_checksum.active_storage.rb
  db/schema.rb
  package.json
  spec/models/support/case_spec.rb
  spec/views/support/save_attachments/new.html.erb_spec.rb
  yarn.lock
Labels: enhancement, in-qa-env

#1053 WIP New end-to-end CI pipeline
  .github/workflows/__archive/clone-contentful-staging-to-develop.yml
  .github/workflows/__archive/continuous-integration.yml
  .github/workflows/__archive/deploy.yml
  .github/workflows/__archive/qa-deploy.yml
  .github/workflows/actions/build-docker-image/action.yml
  .github/workflows/actions/deploy/action.yml
  .github/workflows/ci-full-pipeline.yml
  .github/workflows/ci-release-production.yml
  .github/workflows/qa-cleanup.yml
  .github/workflows/support-knapsack-generate-json.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  Rakefile
  app/controllers/support/agents_controller.rb
  app/services/content/page/build.rb
  config/initializers/flipper.rb
  knapsack_rspec_report.json
  lib/code_coverage_collate.rb
  script/deploy-terraform
  script/qa/destroy
  spec/spec_helper.rb
Labels: qa-seeded, qa-7, qa-deployed, qa-1

#1099 Added survey status and user ip collection
  app/controllers/exit_survey/hear_about_service_controller.rb
  app/controllers/exit_survey/opt_in_controller.rb
  app/controllers/exit_survey/satisfaction_controller.rb
  app/jobs/support/send_exit_survey_job.rb
  app/models/exit_survey_response.rb
  db/migrate/20220810112447_add_status_to_exit_surveys.rb
  db/schema.rb
Labels: qa-seeded, qa-deployed, qa-3

#1102 Removal of Resolved Cases from "My Cases" List in CMS
  app/controllers/support/cases_controller.rb
  app/views/support/cases/index.html.erb
  config/locales/en.yml
  spec/features/support/case_list_spec.rb
Labels: enhancement, in-qa-env, qa-seeded, qa-deployed, qa-5

#1105 Update gems and node dependencies
  Gemfile.lock
  package.json
  yarn.lock
Labels: ruby, javascript, qa-seeded, qa-deployed, qa-5

#1111 Gem updates
  Gemfile.lock
Labels: ruby, qa-seeded, qa-deployed, qa-3

#1122 Record exit survey start date
  .rubocop_todo.yml
  app/controllers/exit_survey/satisfaction_controller.rb
  app/models/exit_survey_response.rb
  db/migrate/20220824084204_add_survey_started_to_exit_survey_responses.rb
  db/schema.rb
  spec/models/exit_survey_response_spec.rb
Labels: qa-skip
