Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-04, with the labels that each got.

#942 Select a framework when adding Procurement Details in CM
  app/controllers/support/cases/procurement_details_controller.rb
  app/controllers/support/frameworks_controller.rb
  app/forms/support/case_procurement_details_form.rb
  app/forms/support/case_procurement_details_form_schema.rb
  app/models/support/framework.rb
  app/models/support/procurement.rb
  app/presenters/support/framework_presenter.rb
  app/presenters/support/procurement_presenter.rb
  app/services/support/seed_frameworks.rb
  app/views/support/cases/procurement_details/edit.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220316140401_create_support_frameworks.rb
  db/migrate/20220316145047_add_framework_to_support_procurements.rb
  db/migrate/20220323155445_update_support_case_data_to_version_3.rb
  db/migrate/20220323155649_remove_framework_name_from_support_procurements.rb
  db/schema.rb
  db/views/support_case_data_v03.sql
  lib/support/frameworks/information.rb
  lib/support/frameworks/mapper.rb
  lib/support/frameworks/record_keeper.rb
  lib/support/frameworks/schema.rb
  lib/tasks/case_management.rake
  spec/factories/support/framework.rb
  spec/factories/support/procurement.rb
  spec/features/support/case_procurement_details_spec.rb
  spec/features/support/procurement_details/edit_procurment_details_spec.rb
  spec/fixtures/frameworks/example_framework_data.csv
  spec/lib/support/frameworks/information_call_spec.rb
  spec/lib/support/frameworks/mapper_call_spec.rb
  spec/lib/support/frameworks/record_keeper_spec.rb
  spec/lib/support/frameworks/schema_call_spec.rb
  spec/models/support/framework_spec.rb
  spec/models/support/procurement_spec.rb
  spec/presenters/support/framework_presenter_spec.rb
  spec/presenters/support/procurement_presenter_spec.rb
  spec/services/support/seed_frameworks_spec.rb
  spec/support/shared/frameworks.rb
Labels: enhancement, in-qa-env

#944 Ability to find a Proc Ops user when assigning a case
  app/controllers/support/cases/assignments_controller.rb
  app/models/support/agent.rb
  app/presenters/support/agent_presenter.rb
  app/views/support/cases/assignments/new.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/case_assignment_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/models/support/agent_spec.rb
  spec/presenters/support/agent_presenter_spec.rb
Labels: enhancement, in-qa-env

#946 add case source and problem description to case creation
  app/controllers/support/cases/previews_controller.rb
  app/controllers/support/cases_controller.rb
  app/forms/support/create_case_form.rb
  app/forms/support/create_case_form_schema.rb
  app/models/support/case.rb
  app/models/support/interaction.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/case_history/_details.html.erb
  app/views/support/cases/forms/_create_case_form.html.erb
  app/views/support/cases/previews/new.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  spec/features/support/case_description_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/features/support/create_case_spec.rb
  spec/forms/support/create_case_form_spec.rb
  spec/models/support/case_spec.rb
  spec/models/support/interaction_spec.rb
Labels: in-qa-env

#953 WIP : update qa deploy to enable static routes
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .github/workflows/qa-deploy.yml
  Gemfile.lock
  script/deploy-terraform
  script/install-cf
  script/qa/cf-login
  script/qa/get-free-dsi-redirect-route
  script/qa/map-static-route
  script/qa/seed
Labels: in-qa-env

#954 Add exit survey template to CMS
  app/services/support/email_templates.rb
  app/views/support/cases/emails/templates/index.html.erb
  config/locales/en.yml
  spec/features/support/emails/agent_sends_templated_email_spec.rb
Labels: enhancement, in-qa-env

#957 Fix type on school source
  app/views/support/cases/forms/_create_case_form.html.erb
Labels: in-qa-env

#966 Added semantic logging
  Gemfile
  Gemfile.lock
  config/environments/development.rb
  config/environments/production.rb
  config/initializers/rails_semantic_logger.rb
Labels: in-qa-env

#967 Specify Feedback links to go to the Qualtrics survey
  app/helpers/application_helper.rb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  db/schema.rb
  spec/features/self-serve/feedback/feedback_spec.rb
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/landing/environment_banner_spec.rb
  spec/helpers/self-serve/application_helper_spec.rb
  spec/models/support/case_spec.rb
Labels: enhancement, in-qa-env

#975 Case navigation back link
  app/controllers/support/application_controller.rb
  app/controllers/support/cases_controller.rb
  app/views/support/cases/_row.erb
  spec/features/support/case_navigation_spec.rb
Labels: enhancement, in-qa-env

#974 Disable validation for unused Support Request field
  app/forms/support_form_schema.rb
  config/locales/validation/en.yml
Labels: bug, in-qa-env

#976 Record date/time survey sent 488 and 489
  db/migrate/20220421093823_update_support_case_data_to_version_4.rb
  db/schema.rb
  db/views/support_case_data_v04.sql
  spec/models/support/case_datum_spec.rb
Labels: enhancement, in-qa-env

#970 Add a confirmation page before 'Close' case action concludes
  Gemfile.lock
  app/controllers/support/cases/closures_controller.rb
  app/views/support/cases/_case_actions.html.erb
  app/views/support/cases/closures/new.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/support/case_closure_spec.rb
Labels: enhancement, in-qa-env

#978 Split out messaging from case history
  .rubocop_todo.yml
  app/assets/stylesheets/base/_misc.scss
  app/controllers/support/email_read_status_controller.rb
  app/models/support/interaction.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/email_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/_case_history.html.erb
  app/views/support/cases/_messages.html.erb
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/cases/case_history/_support_request_body.html.erb
  app/views/support/cases/emails/_unread_badge.html.erb
  app/views/support/cases/messages/_actions.html.erb
  app/views/support/cases/messages/_attachments.html.erb
  app/views/support/cases/messages/_message.html.erb
  app/views/support/cases/messages/_outlook_message.html.erb
  app/views/support/cases/show.html.erb
  app/views/support/emails/show.html.erb
  config/i18n-tasks.yml
  config/locales/en.yml
  script/qa/get-free-dsi-redirect-route
  spec/features/support/case_attachments/agent_can_save_attachments_to_case_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/features/support/emails/agent_can_mark_email_as_read_spec.rb
  spec/features/support/emails/agent_sees_emails_in_messages_spec.rb
  spec/features/support/emails/agent_sees_list_of_emails_spec.rb
  spec/features/support/interactions/list_interactions_spec.rb
  spec/features/support/interactions/new_interaction_spec.rb
  spec/presenters/support/case_presenter_spec.rb
Labels: enhancement, in-qa-env
