Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-03, with the labels that each got.

#887 Case worker can reopen a resolved case
  CHANGELOG.case_management.md
  Gemfile
  Gemfile.lock
  app/controllers/support/cases/assignments_controller.rb
  app/controllers/support/cases/closures_controller.rb
  app/controllers/support/cases/on_holds_controller.rb
  app/controllers/support/cases/openings_controller.rb
  app/controllers/support/cases/resolutions_controller.rb
  app/controllers/support/cases_controller.rb
  app/models/support/case.rb
  app/models/support/email.rb
  app/models/support/interaction.rb
  app/presenters/support/interaction_presenter.rb
  app/services/support/incoming_emails/case_assignment.rb
  app/services/support/merge_case_emails.rb
  app/views/support/cases/_case_actions.html.erb
  config/locales/en.yml
  config/routes.rb
  doc/architecture/decisions/0024-use-aasm-to-manage-support-case-state.md
  spec/factories/support/case.rb
  spec/factories/support/interaction.rb
  spec/features/support/case_closure_spec.rb
  spec/features/support/case_merge_emails_spec.rb
  spec/features/support/case_on_hold_spec.rb
  spec/features/support/case_opening_spec.rb
  spec/features/support/case_summary_spec.rb
  spec/models/support/case_spec.rb
  spec/models/support/email_spec.rb
  spec/models/support/interaction_spec.rb
  spec/requests/support/case_closure_spec.rb
  spec/requests/support/case_on_hold_spec.rb
  spec/requests/support/case_opening_spec.rb
  spec/services/support/incoming_emails/case_assignment_spec.rb
  spec/services/support/merge_case_emails_spec.rb
Labels: enhancement

#899 Ability to update problem description on a case
  CHANGELOG.case_management.md
  app/controllers/support/cases_controller.rb
  app/forms/support/edit_case_form.rb
  app/forms/support/edit_case_form_schema.rb
  app/presenters/support/case_presenter.rb
  app/views/support/cases/_case_details.html.erb
  app/views/support/cases/edit.html.erb
  config/locales/en.yml
  spec/features/support/case_description_spec.rb
  spec/forms/support/create_case_form_spec.rb
  spec/forms/support/edit_case_form_spec.rb
  spec/presenters/support/case_presenter_spec.rb
Labels: enhancement

#905 Feature/484 realtime mi
  CHANGELOG.case_management.md
  app/controllers/support/case_statistics_controller.rb
  app/models/support/case_datum.rb
  app/views/layouts/_navigation_links.html.erb
  app/views/support/case_statistics/show.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20220223124157_create_support_case_data.rb
  db/schema.rb
  db/views/support_case_data_v01.sql
  spec/factories/support/case.rb
  spec/features/support/case_statistics_spec.rb
  spec/models/support/case_datum_spec.rb
Labels: enhancement

#922 Qa app config and workflows
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  .github/workflows/pr-tasks.yml
  .github/workflows/qa-cleanup.yml
  .github/workflows/qa-deploy.yml
  script/deploy-terraform
  script/install-cf
  script/qa/destroy
  script/qa/seed
  terraform/app/locals.tf
  terraform/app/variables.tf
Labels: in-qa-env

#926 Add case summary section to case details tab
  app/controllers/support/cases/contracts_controller.rb
  app/controllers/support/cases/procurement_details_controller.rb
  app/controllers/support/cases/savings_controller.rb
  app/controllers/support/cases/summaries_controller.rb
  app/controllers/support/cases/summary_submissions_controller.rb
  app/forms/support/case_summary_form.rb
  app/forms/support/case_summary_form_schema.rb
  app/services/support/record_action.rb
  app/views/support/cases/_case_details.html.erb
  app/views/support/cases/_procurement_details.html.erb
  app/views/support/cases/show.html.erb
  app/views/support/cases/summaries/edit.html.erb
  app/views/support/cases/summary_submissions/edit.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  db/migrate/20220308110931_add_value_to_support_case.rb
  db/schema.rb
  spec/features/support/agent_can_change_case_summary_spec.rb
  spec/features/support/case_description_spec.rb
  spec/features/support/case_procurement_details_spec.rb
  spec/features/support/case_summary_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/features/support/create_case_spec.rb
  spec/features/support/procurement_details/edit_existing_contract_spec.rb
  spec/features/support/procurement_details/edit_new_contract_spec.rb
  spec/features/support/procurement_details/edit_savings_spec.rb
  spec/models/support/case_spec.rb
Labels: enhancement, in-qa-env

#927 When creating a new specification, prompt the user for a descriptive name
  CHANGELOG.md
  app/controllers/categories_controller.rb
  app/controllers/journeys_controller.rb
  app/forms/edit_journey_form.rb
  app/forms/edit_journey_form_schema.rb
  app/forms/new_journey_form.rb
  app/forms/new_journey_form_schema.rb
  app/services/create_category.rb
  app/services/create_journey.rb
  app/services/specification_renderer.rb
  app/views/categories/index.html.erb
  app/views/dashboard/show.html.erb
  app/views/design/index.html.erb
  app/views/journeys/edit.html.erb
  app/views/journeys/new.html.erb
  app/views/journeys/show.html.erb
  app/views/journeys/steps/_back_link.html.erb
  app/views/journeys/steps/_form.html.erb
  app/views/journeys/steps/_step_1.html.erb
  app/views/journeys/steps/_step_2.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20220307145743_add_name_to_journey.rb
  db/schema.rb
  lib/tasks/self_serve.rake
  script/qa/seed
  spec/factories/journey.rb
  spec/factories/user.rb
  spec/features/self-serve/categories/categories_spec.rb
  spec/features/self-serve/dashboard/dashboard_spec.rb
  spec/features/self-serve/dashboard/delete_journey_spec.rb
  spec/features/self-serve/dashboard/existing_journey_spec.rb
  spec/features/self-serve/dashboard/new_journey_spec.rb
  spec/features/self-serve/journeys/category_spec.rb
  spec/features/self-serve/journeys/edit_journey_spec.rb
  spec/features/self-serve/journeys/new_journey_spec.rb
  spec/features/self-serve/journeys/show_journey_spec.rb
  spec/features/self-serve/journeys/task_list/view_steps_spec.rb
  spec/features/self-serve/journeys/view_spec.rb
  spec/forms/self-serve/edit_journey_form_schema_spec.rb
  spec/forms/self-serve/edit_journey_form_spec.rb
  spec/forms/self-serve/new_journey_form_schema_spec.rb
  spec/forms/self-serve/new_journey_form_spec.rb
  spec/lib/tasks/self_serve_spec.rb
  spec/migrations/self-serve/add_default_to_step_tally_spec.rb
  spec/migrations/self-serve/add_missing_order_to_existing_tasks_spec.rb
  spec/migrations/self-serve/associate_existing_journeys_spec.rb
  spec/requests/self-serve/contentful_caching_spec.rb
  spec/services/self-serve/create_category_spec.rb
  spec/services/self-serve/create_journey_spec.rb
  spec/services/self-serve/specification_renderer_spec.rb
  spec/support/journey_helpers.rb
  spec/support/shared/migrations.rb
Labels: enhancement, in-qa-env

#923 [412,408,413] Make state changes visible in Case history as an Interaction
  .rubocop_todo.yml
  app/controllers/support/cases/application_controller.rb
  app/controllers/support/cases/closures_controller.rb
  app/controllers/support/cases/merge_emails_controller.rb
  app/controllers/support/cases/on_holds_controller.rb
  app/controllers/support/cases/openings_controller.rb
  app/controllers/support/cases/resolutions_controller.rb
  app/models/support/case.rb
  app/models/support/case_datum.rb
  app/models/support/interaction.rb
  app/presenters/support/interaction_presenter.rb
  app/services/support/change_case_state.rb
  app/services/support/merge_case_emails.rb
  config/locales/en.yml
  db/migrate/20220310153239_add_closure_reason_to_support_cases.rb
  db/migrate/20220310170158_change_closure_reason_to_enum.rb
  db/migrate/20220316155306_update_support_case_data_to_version_2.rb
  db/schema.rb
  db/views/support_case_data_v02.sql
  spec/features/support/case_closure_spec.rb
  spec/features/support/case_merge_emails_spec.rb
  spec/features/support/case_on_hold_spec.rb
  spec/features/support/case_opening_spec.rb
  spec/features/support/case_resolution_spec.rb
  spec/models/support/case_datum_spec.rb
  spec/models/support/case_spec.rb
  spec/models/support/interaction_spec.rb
  spec/requests/support/case_closure_spec.rb
  spec/services/support/merge_case_emails_spec.rb
Labels: in-qa-env

#931 349 record extension number
  app/controllers/support/cases/contact_details_controller.rb
  app/controllers/support/cases/previews_controller.rb
  app/controllers/support/cases_controller.rb
  app/forms/support/case_contact_details_form.rb
  app/forms/support/case_contact_details_form_schema.rb
  app/forms/support/create_case_form.rb
  app/forms/support/create_case_form_schema.rb
  app/services/support/create_case.rb
  app/views/support/cases/_school_details.html.erb
  app/views/support/cases/contact_details/edit.html.erb
  app/views/support/cases/forms/_create_case_form.html.erb
  app/views/support/cases/previews/new.html.erb
  config/locales/en.yml
  db/migrate/20220315104542_add_extension_number_to_support_cases.rb
  db/schema.rb
  spec/features/support/agent_can_set_case_contact_spec.rb
  spec/features/support/case_organisation_details_spec.rb
  spec/features/support/case_school_details_spec.rb
  spec/models/support/case_spec.rb
  spec/services/support/create_case_spec.rb
Labels: in-qa-env

#930 Replace links in emails with the href text
  app/presenters/support/email_presenter.rb
  app/views/support/emails/show.html.erb
  config/brakeman.ignore
  script/test
  spec/presenters/support/email_presenter_spec.rb
Labels: in-qa-env

#936 Record notify email correctly in case history
  .github/pull_request_template.md
  .github/workflows/continuous-integration.yml
  app/controllers/support/cases/emails/content_controller.rb
  app/controllers/support/cases/emails/types_controller.rb
  app/controllers/support/cases/emails_controller.rb
  app/controllers/support/interactions_controller.rb
  app/forms/support/case_email_content_form.rb
  app/forms/support/case_email_content_form_schema.rb
  app/presenters/support/interaction_presenter.rb
  app/services/support/email_templates.rb
  app/views/support/cases/case_history/_details.html.erb
  app/views/support/cases/emails/content/edit.html.erb
  app/views/support/cases/emails/content/show.html.erb
  app/views/support/cases/emails/templates/index.html.erb
  app/views/support/interactions/show.html.erb
  config/brakeman.ignore
  config/locales/en.yml
  config/locales/validation/support/en.yml
  db/schema.rb
  script/check-coverage
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
  spec/models/support/case_spec.rb
Labels: in-qa-env

#941 Remove case worker link
  app/views/layouts/_navigation_links.html.erb
  app/views/layouts/application.html.erb
  app/views/support/cases/show.html.erb
  spec/features/support/case_tabs_spec.rb
Labels: in-qa-env

#940 Referrer on FaF requests
  app/controllers/framework_request_submissions_controller.rb
  app/controllers/framework_requests_controller.rb
  app/controllers/sessions_controller.rb
  app/services/submit_framework_request.rb
  config/locales/en.yml
  spec/controllers/framework_requests_controller_spec.rb
Labels: in-qa-env

#937 [363] Mark spec finished
  app/assets/javascripts/redirect.js
  app/assets/stylesheets/base/_misc.scss
  app/controllers/specifications_controller.rb
  app/forms/download_specification_form.rb
  app/forms/download_specification_form_schema.rb
  app/models/journey.rb
  app/presenters/journey_presenter.rb
  app/views/dashboard/show.html.erb
  app/views/layouts/_redirect.html.erb
  app/views/layouts/application.html.erb
  app/views/specifications/new.html.erb
  app/views/specifications/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20220322085246_add_finished_at_to_journey.rb
  db/schema.rb
  spec/features/self-serve/dashboard/delete_journey_spec.rb
  spec/features/self-serve/dashboard/existing_journey_spec.rb
  spec/features/self-serve/journeys/download_spec.rb
  spec/features/self-serve/journeys/view_spec.rb
  spec/features/self-serve/metrics/log_view_specification_spec.rb
  spec/models/support/case_spec.rb
Labels: in-qa-env
