Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-06, with the labels that each got.

#1001 Add triage questions to specify & FaF support requests
  app/assets/config/manifest.js
  app/assets/javascripts/request/common.js
  app/assets/javascripts/request/procurement_amount.js
  app/assets/javascripts/request/special_requirements.js
  app/controllers/framework_requests_controller.rb
  app/controllers/support_requests_controller.rb
  app/forms/framework_support_form.rb
  app/forms/framework_support_form_schema.rb
  app/forms/request_form.rb
  app/forms/request_form_schema.rb
  app/forms/support_form.rb
  app/forms/support_form_schema.rb
  app/models/framework_request.rb
  app/models/request.rb
  app/models/support_request.rb
  app/presenters/framework_request_presenter.rb
  app/presenters/request_presenter.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support_request_presenter.rb
  app/services/submit_framework_request.rb
  app/services/submit_support_request.rb
  app/services/support/create_case.rb
  app/views/framework_requests/show.html.erb
  app/views/framework_requests/steps/_form.html.erb
  app/views/framework_requests/steps/_step_10.html.erb
  app/views/framework_requests/steps/_step_8.html.erb
  app/views/framework_requests/steps/_step_9.html.erb
  app/views/requests/_form/_confidence_level.html.erb
  app/views/requests/_form/_procurement_amount.html.erb
  app/views/requests/_form/_special_requirements.html.erb
  app/views/support/cases/_case_details.html.erb
  app/views/support_requests/_form/_form.html.erb
  app/views/support_requests/_form/_step_6.html.erb
  app/views/support_requests/_form/_step_7.html.erb
  app/views/support_requests/_form/_step_8.html.erb
  app/views/support_requests/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  db/migrate/20220512094004_add_triage_attributes_to_requests.rb
  db/migrate/20220520071637_add_triage_attributes_to_cases.rb
  db/schema.rb
  spec/factories/framework_requests.rb
  spec/factories/support_request.rb
  spec/features/self-serve/framework_requests/create_framework_request_dsi_spec.rb
  spec/features/self-serve/framework_requests/create_framework_request_guest_spec.rb
  spec/features/self-serve/support_requests/create_support_request_spec.rb
  spec/features/self-serve/support_requests/edit_support_request_spec.rb
  spec/features/support/case_description_spec.rb
  spec/features/support/case_procurement_details_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/forms/self-serve/request_form_schema_spec.rb
  spec/forms/self-serve/request_form_spec.rb
  spec/models/support/case_spec.rb
  spec/presenters/self-serve/request_presenter_spec.rb
Labels: enhancement, in-qa-env

#1036 SubmitFrameworkRequest bugfix
  app/services/submit_framework_request.rb
Labels: bug, in-qa-env

#1039 Ability to move category from 1 parent to another
  app/helpers/support/collection_helper.rb
  app/models/support/category.rb
  config/support/categories.yml
  lib/tasks/case_management.rake
  spec/helpers/support/collection_helper_spec.rb
  spec/models/support/category_spec.rb
Labels: in-qa-env

#1038 Change references to category to sub-category
  app/views/support/case_statistics/show.html.erb
  app/views/support/cases/_case_details.html.erb
  app/views/support/cases/closures/new.html.erb
  app/views/support/cases/forms/_filter_cases_form.html.erb
  app/views/support/cases/index.html.erb
  app/views/support/cases/previews/new.html.erb
  app/views/support/cases/request_details/_form_fields.html.erb
  app/views/support/cases/request_details/update.html.erb
  app/views/support/cases/searches/index.html.erb
  config/locales/en.yml
  db/migrate/20220622125156_update_support_case_data_to_version_6.rb
  db/views/support_case_data_v06.sql
  spec/features/support/case_closure_spec.rb
  spec/features/support/case_list_spec.rb
  spec/features/support/case_navigation_spec.rb
  spec/features/support/case_statistics_spec.rb
  spec/features/support/case_tabs_spec.rb
  spec/models/support/case_datum_spec.rb
  spec/support/tinymce_helpers.rb
Labels: enhancement, in-qa-env

#1033 Exit survey automation
  .env.example
  app/assets/stylesheets/components/supported/_email-preview.scss
  app/controllers/support/cases/emails/content_controller.rb
  app/controllers/support/cases/resolutions_controller.rb
  app/jobs/support/send_exit_survey_job.rb
  app/services/emails/exit_survey.rb
  config/locales/en.yml
  db/migrate/20220610125240_add_exit_survey_sent_to_cases.rb
  db/schema.rb
  lib/notify/email.rb
  spec/features/support/case_resolution_spec.rb
  spec/jobs/support/send_exit_survey_job_spec.rb
  spec/models/support/case_spec.rb
  spec/services/self-serve/emails/exit_survey_spec.rb
Labels: enhancement, in-qa-env

#1040 Remove exit survey from templates
  app/views/support/cases/emails/templates/index.html.erb
  config/locales/en.yml
  spec/features/support/emails/agent_sends_templated_email_spec.rb
Labels: in-qa-env

#1041 Feature/1017 add tower filter
  app/forms/support/case_filter_form.rb
  app/models/support/case.rb
  app/models/support/category.rb
  app/presenters/support/category_presenter.rb
  app/services/support/filter_cases.rb
  app/services/support/seed_categories.rb
  app/views/support/cases/forms/_filter_cases_form.html.erb
  config/locales/en.yml
  config/support/categories.yml
  db/migrate/20220622100544_add_tower_to_support_categories.rb
  db/schema.rb
  spec/factories/support/category.rb
  spec/services/support/filter_cases_spec.rb
Labels: enhancement, in-qa-env
