Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-11, with the labels that each got.

#1207 Ignore bots when tracking user journeys
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/framework_requests/base_controller.rb
  app/controllers/framework_requests/start_controller.rb
  app/controllers/framework_requests_controller.rb
  config/application.rb
  lib/middleware/user_journey_tracking.rb
  spec/requests/user_journey/user_journey_tracking_spec.rb
Labels: qa-seeded, qa-deployed, qa-5

#1209 All Cases Survey
  .rubocop_todo.yml
  app/controllers/all_cases_survey/about_outcomes_controller.rb
  app/controllers/all_cases_survey/accessibility_research_controller.rb
  app/controllers/all_cases_survey/base_controller.rb
  app/controllers/all_cases_survey/improvements_controller.rb
  app/controllers/all_cases_survey/outcome_achieved_controller.rb
  app/controllers/all_cases_survey/satisfaction_controller.rb
  app/controllers/all_cases_survey/satisfaction_reason_controller.rb
  app/controllers/all_cases_survey/start_controller.rb
  app/controllers/all_cases_survey/thank_you_controller.rb
  app/controllers/support/management/all_cases_surveys_controller.rb
  app/forms/all_cases_survey/about_outcomes_form.rb
  app/forms/all_cases_survey/accessibility_research_form.rb
  app/forms/all_cases_survey/base_form.rb
  app/forms/all_cases_survey/improvements_form.rb
  app/forms/all_cases_survey/outcome_achieved_form.rb
  app/forms/all_cases_survey/satisfaction_form.rb
  app/forms/all_cases_survey/satisfaction_reason_form.rb
  app/jobs/support/send_all_cases_survey_job.rb
  app/models/all_cases_survey_response.rb
  app/models/support/case.rb
  app/presenters/all_cases_survey_response_presenter.rb
  app/services/emails/all_cases_survey.rb
  app/services/emails/all_cases_survey_open.rb
  app/services/emails/all_cases_survey_resolved.rb
  app/services/support/email_templates.rb
  app/views/all_cases_survey/about_outcomes/edit.html.erb
  app/views/all_cases_survey/accessibility_research/edit.html.erb
  app/views/all_cases_survey/improvements/edit.html.erb
  app/views/all_cases_survey/outcome_achieved/edit.html.erb
  app/views/all_cases_survey/satisfaction/edit.html.erb
  app/views/all_cases_survey/satisfaction_reason/edit.html.erb
  app/views/all_cases_survey/start/show.html.erb
  app/views/all_cases_survey/thank_you/show.html.erb
  app/views/support/management/all_cases_surveys/index.html.erb
  app/views/support/management/base/index.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20221028153815_create_all_cases_survey_responses.rb
  db/migrate/20221102140902_add_accessibility_research_to_all_cases_survey_responses.rb
  db/migrate/20221103100620_add_accessibility_research_email_to_all_cases_survey_responses.rb
  db/migrate/20221103100733_add_sent_and_completed_dates_to_all_cases_survey_responses.rb
  db/schema.rb
  spec/factories/all_cases_survey_response.rb
  spec/features/all_cases_survey/all_cases_survey_spec.rb
  spec/forms/all_cases_survey/about_outcomes_form_spec.rb
  spec/forms/all_cases_survey/accessibility_research_form_spec.rb
  spec/forms/all_cases_survey/base_form_spec.rb
  spec/forms/all_cases_survey/improvements_form_spec.rb
  spec/forms/all_cases_survey/outcome_achieved_form_spec.rb
  spec/forms/all_cases_survey/satisfaction_form_spec.rb
  spec/forms/all_cases_survey/satisfaction_reason_form_spec.rb
  spec/jobs/support/send_all_cases_survey_job_spec.rb
  spec/models/all_cases_survey_response_spec.rb
  spec/presenters/all_cases_survey_response_presenter_spec.rb
  spec/services/self-serve/emails/all_cases_survey_spec.rb
Labels: qa-seeded, qa-deployed, qa-4

#1215 Add missing organisation validation in RFH
  app/forms/framework_requests/search_for_organisation_form.rb
  spec/forms/framework_requests/search_for_organisation_form_spec.rb
Labels: bug, qa-seeded, qa-deployed, qa-4

#1217 Fix bug where current_user_journey helper doesnt work for non GET requests
  lib/middleware/user_journey_tracking.rb
Labels: qa-seeded, qa-deployed, qa-4

#1220 Specification CSS updates
  app/assets/stylesheets/components/_page.scss
Labels: enhancement, qa-seeded, qa-6, qa-deployed

#1219 Add links to case statistics
  app/controllers/support/towers_controller.rb
  app/forms/support/case_filter_form.rb
  app/helpers/support/case_statistics_helper.rb
  app/models/support/case.rb
  app/models/support/case_statistics.rb
  app/views/support/case_statistics/show.html.erb
  app/views/support/case_statistics/towers/show.html.erb
  app/views/support/cases/forms/_simple_case_filters.html.erb
  config/locales/en.yml
  spec/features/support/case_statistics_spec.rb
  spec/features/support/towers_spec.rb
  spec/helpers/support/case_statistics_helper_spec.rb
Labels: enhancement, qa-seeded, qa-deployed, qa-5

#1218 Auto assign categories
  Gemfile.lock
  app/assets/stylesheets/base/_misc.scss
  app/controllers/support/cases/request_details_controller.rb
  app/controllers/support/management/category_detections_controller.rb
  app/forms/support/case_filter_form.rb
  app/forms/support/case_request_details_form.rb
  app/forms/support/category_detection_form.rb
  app/forms/support/concerns/request_details_form_fields.rb
  app/helpers/support/collection_helper.rb
  app/javascript/components/tinymce.js
  app/models/support/case.rb
  app/models/support/category.rb
  app/models/support/category_detection.rb
  app/models/support/category_detection_stats.rb
  app/models/support/interaction.rb
  app/presenters/support/case_categorisation_change_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/services/submit_framework_request.rb
  app/services/support/case_categorisation_change_logger.rb
  app/services/support/create_case.rb
  app/services/support/seed_categories.rb
  app/views/support/cases/case_history/_case_categorisation_changed.html.erb
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/management/agents/index.html.erb
  app/views/support/management/all_cases_surveys/index.html.erb
  app/views/support/management/base/index.html.erb
  app/views/support/management/categories/index.html.erb
  app/views/support/management/category_detections/new.html.erb
  config/locales/en.yml
  config/routes.rb
  config/support/categories.yml
  config/support/category_stop_words.txt
  db/migrate/20221115145634_enable_pg_trgm_extension.rb
  db/migrate/20221115145635_add_detected_category_id_to_support_cases.rb
  db/migrate/20221117102647_add_archived_to_support_categories.rb
  db/schema.rb
  script/gpaas/production/rails
  script/gpaas/production/rails_c
  script/gpaas/qa/rails
  script/gpaas/qa/rails_c
  script/gpaas/staging/rails
  script/gpaas/staging/rails_c
  spec/features/self-serve/framework_requests/edit_framework_request_guest_spec.rb
  spec/features/support/management/admin_can_debug_category_detection_spec.rb
  spec/helpers/support/collection_helper_spec.rb
  spec/models/support/case_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/create_case_form_presenter_spec.rb
  spec/services/self-serve/content/connector_instance_spec.rb
  spec/services/self-serve/submit_framework_request_spec.rb
  spec/services/support/case_categorisation_change_logger_spec.rb
  spec/services/support/seed_categories_spec.rb
  yarn.lock
Labels: qa-seeded, qa-deployed, qa-4

#1229 Assign inferred org in RFH form
  app/controllers/framework_requests/confirm_sign_in_controller.rb
  app/views/framework_requests/confirm_sign_in/index.html.erb
  spec/features/self-serve/framework_requests/create_framework_request_dsi_spec.rb
Labels: bug, qa-seeded, qa-deployed, qa-5
