Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-02, with the labels that each got.

#828 List of All Cases in CM is showing the creation date in the 'Last updated' column
  app/controllers/support/cases/contracts_controller.rb
  app/controllers/support/cases/procurement_details_controller.rb
  app/controllers/support/cases/savings_controller.rb
  app/controllers/support/cases_controller.rb
  app/controllers/support/concerns/has_interaction.rb
  app/models/support/interaction.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/case_history/_interaction.html.erb
  spec/factories/support/interaction.rb
  spec/features/self-serve/dashboard/existing_journey_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/case_presenter_spec.rb
  spec/presenters/support/interaction_presenter_spec.rb
Labels: bug

#845 List of All Cases in CM is showing the creation date in the 'Last updated' column
  app/controllers/support/cases_controller.rb
  app/presenters/support/case_presenter.rb
Labels: bug

#850 FaF MAT n Feds - Group search page
  app/controllers/framework_request_submissions_controller.rb
  app/controllers/framework_requests_controller.rb
  app/controllers/support/establishment_groups_controller.rb
  app/controllers/support/organisations_controller.rb
  app/forms/framework_support_form.rb
  app/forms/framework_support_form_schema.rb
  app/models/support/establishment_group.rb
  app/views/framework_requests/steps/_search_for_a_group.html.erb
  app/views/framework_requests/steps/_search_for_a_school.html.erb
  app/views/framework_requests/steps/_step_5.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20220204135146_add_group_uid_to_framework_requests.rb
  db/schema.rb
  spec/factories/framework_requests.rb
  spec/factories/support/support_establishment_group.rb
  spec/features/self-serve/faf/create_framework_request_no_dsi_spec.rb
  spec/features/self-serve/faf/edit_framework_request_spec.rb
  spec/features/self-serve/faf/session_spec.rb
  spec/features/self-serve/faf/start_page_spec.rb
  spec/features/self-serve/faf/submit_framework_request_spec.rb
  spec/features/self-serve/faf/update_request_spec.rb
Labels: enhancement

#863 FaF Support Request - Modify eligibility check so MATs are eligible
  app/services/create_user.rb
  config/initializers/school_types.rb
  spec/factories/user.rb
  spec/features/self-serve/auth/supported_user_spec.rb
Labels: enhancement

#870 FaF MAT and Feds is this the group or trust page
  app/controllers/framework_requests_controller.rb
  app/forms/framework_support_form.rb
  app/forms/framework_support_form_schema.rb
  app/views/framework_requests/steps/_form.html.erb
  app/views/framework_requests/steps/_step_4.html.erb
  config/locales/validation/en.yml
  spec/features/self-serve/faf/create_framework_request_no_dsi_spec.rb
Labels: bug

#855 FaF support request - updates to DfE signed in journey for MATs
  app/assets/javascripts/faf_select_school.js
  app/controllers/framework_requests_controller.rb
  app/forms/framework_support_form.rb
  app/forms/framework_support_form_schema.rb
  app/presenters/user_presenter.rb
  app/views/framework_requests/show.html.erb
  app/views/framework_requests/steps/_step_3.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  spec/factories/user.rb
  spec/features/self-serve/auth/supported_user_spec.rb
  spec/features/self-serve/faf/create_framework_request_spec.rb
  spec/features/self-serve/faf/edit_framework_request_spec.rb
  spec/presenters/self-serve/user_presenter_spec.rb
Labels: enhancement

#888 Pass all arguments to rspec within docker
  script/spec
Labels: enhancement, refactor

#890 adds details page for feedback
  CHANGELOG.md
  app/controllers/feedback_controller.rb
  app/forms/feedback_form.rb
  app/forms/feedback_form_schema.rb
  app/models/user_feedback.rb
  app/views/feedback/_details_submitted.html.erb
  app/views/feedback/_feedback_submitted.html.erb
  app/views/feedback/edit.html.erb
  app/views/feedback/new.html.erb
  app/views/feedback/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20220218085717_add_user_data_to_user_feedback.rb
  db/schema.rb
  spec/features/self-serve/feedback/details_spec.rb
  spec/features/self-serve/feedback/feedback_spec.rb
Labels: enhancement

#885 UR Beta Banner - Feedback page
  CHANGELOG.md
  app/controllers/feedback_controller.rb
  app/forms/feedback_form.rb
  app/forms/feedback_form_schema.rb
  app/helpers/application_helper.rb
  app/models/user_feedback.rb
  app/views/feedback/_details_submitted.html.erb
  app/views/feedback/_feedback_submitted.html.erb
  app/views/feedback/edit.html.erb
  app/views/feedback/new.html.erb
  app/views/feedback/show.html.erb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/routes.rb
  db/migrate/20220216170254_create_user_feedback.rb
  db/migrate/20220218085717_add_user_data_to_user_feedback.rb
  db/schema.rb
  spec/factories/user_feedback.rb
  spec/features/self-serve/feedback/details_spec.rb
  spec/features/self-serve/feedback/feedback_spec.rb
  spec/features/self-serve/landing/environment_banner_spec.rb
  spec/helpers/self-serve/application_helper_spec.rb
Labels: enhancement

#894 Update feedback page content
  app/controllers/feedback_controller.rb
  app/views/feedback/_details_submitted.html.erb
  config/locales/en.yml
  spec/features/self-serve/feedback/details_spec.rb
  spec/features/self-serve/feedback/feedback_spec.rb
Labels: enhancement

#900 last_updated_at is displaying incorrect date
  app/presenters/support/case_presenter.rb
  spec/presenters/support/case_presenter_spec.rb
Labels: bug
