Repository DFE-Digital/buy-for-your-school, pull requests merged in 2022-01, with the labels that each got.

#732 Hide internal team members from assignable case workers
  app/controllers/support/cases/assignments_controller.rb
  app/controllers/tasks_controller.rb
  app/models/support/agent.rb
  db/migrate/20211222162846_add_internal_to_support_agents.rb
  spec/factories/support/agent.rb
  spec/features/support/case_assignment_spec.rb
Labels: bug

#746 Case source being set incorrectly on create a case
  app/forms/support/case_hub_migration_form.rb
  db/schema.rb
  spec/forms/support/case_hub_migration_form_spec.rb
Labels: bug

#747 Hubs migration when there is no establishment
  app/forms/support/case_hub_migration_form_schema.rb
  config/locales/validation/support/en.yml
  spec/features/support/case_migration_spec.rb
Labels: bug

#767 Error on phone number validation
  app/forms/support/case_hub_migration_form_schema.rb
  app/forms/support_form_schema.rb
  config/locales/validation/en.yml
  config/locales/validation/support/en.yml
  spec/factories/support_request.rb
  spec/features/self-serve/support_requests/create_support_request_spec.rb
  spec/features/support/case_migration_spec.rb
Labels: bug

#790 Calculate dates for existing and new contracts
  app/models/support/existing_contract.rb
  app/models/support/new_contract.rb
  spec/features/support/procurement_details/edit_existing_contract_spec.rb
  spec/features/support/procurement_details/edit_new_contract_spec.rb
  spec/models/support/existing_contract_spec.rb
  spec/models/support/new_contract_spec.rb
Labels: enhancement

#797 260 Category and school name not being displayed
  .gitignore
  app/presenters/support/interaction_presenter.rb
  spec/factories/support/category.rb
  spec/factories/support/interaction.rb
  spec/factories/support/organisation.rb
  spec/presenters/support/interaction_presenter_spec.rb
Labels: bug

#798 FaF Support Request - Confirmation page
  app/controllers/fafs_controller.rb
  app/controllers/fafs_submissions_controller.rb
  app/models/support/case.rb
  app/models/support/interaction.rb
  app/presenters/faf_presenter.rb
  app/services/submit_framework_request.rb
  app/views/fafs/edit.html.erb
  app/views/fafs/new.html.erb
  app/views/fafs/show.html.erb
  app/views/fafs/steps/_step_4.html.erb
  app/views/fafs/steps/_step_5.html.erb
  app/views/fafs_submissions/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/factories/framework_requests.rb
  spec/features/self-serve/auth/sign_in_spec.rb
  spec/features/self-serve/faf/check_your_answers_spec.rb
  spec/features/self-serve/faf/confirmation_page_spec.rb
  spec/features/self-serve/faf/contact_info_spec.rb
  spec/features/self-serve/faf/dsi_or_search_spec.rb
  spec/features/self-serve/faf/update_request_spec.rb
  spec/features/self-serve/faf/user_organisation_page_spec.rb
  spec/features/self-serve/faf/user_query_page_spec.rb
  spec/presenters/self-serve/faf_presenter_spec.rb
Labels: enhancement

#802 Add salutation and signature to non-templated email preview
  app/controllers/support/cases/emails/content_controller.rb
  app/controllers/support/cases/emails/types_controller.rb
  app/views/support/cases/emails/content/edit.html.erb
  app/views/support/cases/emails/content/show.html.erb
  config/locales/en.yml
  spec/features/support/emails/agent_sends_basic_email_spec.rb
  spec/features/support/emails/agent_sends_templated_email_spec.rb
Labels: bug

#811 #243 FaF Support Request - Search for a school
  app/controllers/support/organisations_controller.rb
  app/forms/framework_support_form.rb
  app/views/framework_requests/steps/_step_4.html.erb
  config/locales/en.yml
Labels: enhancement

#821 The KPI 'Specify user activity' data to be in JSON format
  app/controllers/admin_controller.rb
  app/views/admin/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/admin/show_spec.rb
Labels: enhancement

#822 FaF Support Request - is this the school? page
  app/assets/javascripts/faf_confirm_school.js
  app/controllers/framework_requests_controller.rb
  app/presenters/support/organisation_presenter.rb
  app/views/framework_requests/show.html.erb
  app/views/framework_requests/steps/_step_5.html.erb
  app/views/framework_requests/steps/_step_6.html.erb
  config/locales/en.yml
  spec/presenters/support/organisation_presenter_spec.rb
Labels: enhancement

#830 Update CHANGELOG for release 19 changes
  CHANGELOG.case_management.md
  CHANGELOG.md
Labels: documentation

#831 Add the user table to the KPI download
  CHANGELOG.md
  app/controllers/admin_controller.rb
  app/views/admin/show.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/features/self-serve/admin/show_spec.rb
Labels: enhancement
