Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-02, with the labels that each got.

#1280 feat(notifications): added notification models
  app/models/support/notification.rb
  app/models/support/notification_assignment.rb
  db/migrate/20230130100805_create_support_notifications.rb
  db/migrate/20230130100815_create_support_notification_assignments.rb
  db/schema.rb
  spec/factories/support/support_notifications.rb
  spec/models/support/notification_assignment_spec.rb
Labels: qa-seeded, qa-7, qa-deployed

#1286 fix: category options should list or last
  app/helpers/support/collection_helper.rb
  app/models/support/category.rb
  spec/support/category_helpers.rb
Labels: qa-seeded, qa-deployed, qa-3

#1273 PWNN-1066: Ability to update case source
  app/controllers/support/cases/summaries_controller.rb
  app/controllers/support/cases/summary_submissions_controller.rb
  app/forms/support/case_summary_form.rb
  app/forms/support/case_summary_form_schema.rb
  app/models/support/interaction.rb
  app/presenters/support/case_source_change_presenter.rb
  app/presenters/support/interaction_presenter.rb
  app/views/support/cases/case_history/_case_source_changed.html.erb
  app/views/support/cases/summaries/edit.html.erb
  app/views/support/cases/summary_submissions/edit.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  spec/factories/support/interaction.rb
  spec/features/support/agent_can_change_case_summary_spec.rb
  spec/forms/support/case_summary_form_schema_spec.rb
  spec/forms/support/case_summary_form_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/case_source_change_presenter_spec.rb
Labels: enhancement, qa-seeded, qa-6, qa-deployed

#1288 feat(rfh): detect only energy tower cats eng reqs
  app/controllers/support/management/category_detections_controller.rb
  app/forms/support/category_detection_form.rb
  app/models/support/category_detection.rb
  app/services/submit_framework_request.rb
  app/views/support/management/category_detections/new.html.erb
  spec/services/self-serve/submit_framework_request_spec.rb
Labels: qa-skip

#1290 fix(rfh): define bill upload button values
  app/javascript/controllers/energy_bill_upload_controller.js
Labels: bug, qa-seeded, qa-deployed, qa-2

#1294 fix(specify): fix next steps links and redirects
  app/controllers/specifications_controller.rb
  app/presenters/journey_presenter.rb
  app/views/specifications/show.html.erb
  spec/controllers/self-serve/specifications_controller_spec.rb
  spec/presenters/self-serve/journey_presenter_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1293 feat(cms): add cases without orgs to satistics
  app/controllers/support/towers_controller.rb
  app/forms/support/case_filter_form.rb
  app/models/support/case.rb
  app/models/support/tower_statistics.rb
  app/services/support/filter_cases.rb
  app/views/support/case_statistics/towers/show.html.erb
  config/locales/en.yml
  db/migrate/20230203151247_update_support_tower_cases_to_version_3.rb
  db/schema.rb
  db/views/support_tower_cases_v03.sql
  spec/models/support/tower_statistics_spec.rb
  spec/services/support/filter_cases_spec.rb
Labels: qa-seeded, qa-deployed, qa-2

#1289 feat(rfh): energy bill flow content tweaks
  app/models/framework_request.rb
  app/views/framework_requests/messages/_form_hint.html.erb
  config/locales/en.yml
  spec/controllers/framework_requests/energy_request_about_controller_spec.rb
  spec/forms/framework_requests/energy_request_about_form_spec.rb
  spec/models/framework_request_spec.rb
  spec/models/self-serve/framework_request_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1302 Fix accessibility audit failures in RFH
  app/assets/stylesheets/components/_autocomplete.scss
  app/controllers/support/establishment_groups_controller.rb
  app/controllers/support/organisations_controller.rb
  app/forms/framework_requests/procurement_amount_form.rb
  app/javascript/components/autocomplete.js
  app/presenters/request_presenter.rb
  app/presenters/support/establishment_group_presenter.rb
  app/presenters/support/organisation_presenter.rb
  app/views/framework_request_submissions/show.html.erb
  app/views/framework_requests/confirm_organisations/_confirm_group.html.erb
  app/views/framework_requests/emails/_form.html.erb
  app/views/framework_requests/procurement_amounts/_form.html.erb
  app/views/framework_requests/procurement_amounts/_form_hint.erb
  app/views/framework_requests/show.html.erb
  config/locales/en.yml
  spec/features/self-serve/framework_requests/create_framework_request_guest_spec.rb
  spec/features/self-serve/support_requests/edit_support_request_spec.rb
  spec/forms/framework_requests/procurement_amount_form_spec.rb
  spec/presenters/self-serve/request_presenter_spec.rb
  spec/presenters/support/establishment_group_presenter_spec.rb
  spec/presenters/support/organisation_presenter_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1312 feat(cms): prepopulate case stage, level, value
  app/services/support/create_case.rb
  spec/services/support/create_case_spec.rb
Labels: qa-seeded, qa-deployed, qa-2
