Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-07, with the labels that each got.

#1467 1527 - fix(rfh): fix missing category mappings
  config/request_for_help/categories.yml
  config/support/categories.yml
  spec/services/support/seed_categories_spec.rb
Labels: qa-seeded, qa-deployed, qa-4

#1468 1459 - feat(cms): triage view
  app/controllers/support/cases_controller.rb
  app/controllers/support/concerns/filter_parameters.rb
  app/controllers/support/towers_controller.rb
  app/helpers/support/case_statistics_helper.rb
  app/models/support/case.rb
  app/models/support/tower.rb
  app/views/support/cases/forms/_simple_case_filters.html.erb
  app/views/support/cases/index.html.erb
  app/views/support/cases/index/_tab_triage_cases.html.erb
  config/locales/en.yml
  spec/features/self-serve/admin/show_spec.rb
  spec/features/support/case_list_spec.rb
  spec/features/support/towers_spec.rb
  spec/models/support/case_spec.rb
  spec/rails_helper.rb
Labels: qa-seeded, qa-deployed, qa-5

#1466 1520 - feat(cms): persist user selected category on case
  app/models/support/case.rb
  app/services/submit_framework_request.rb
  app/services/support/create_case.rb
  app/views/support/cases/show/_case_details.html.erb
  config/locales/en.yml
  db/migrate/20230627133137_add_user_selected_category_to_support_cases.rb
  db/schema.rb
  spec/features/support/case_tabs_spec.rb
  spec/models/support/case_spec.rb
  spec/services/self-serve/submit_framework_request_spec.rb
  spec/services/support/create_case_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1393 Get repo running on azure
  .gitignore
  Gemfile
  Gemfile.lock
  app/views/layouts/application.html.erb
  config/environments/production.rb
  config/initializers/content_security_policy.rb
  config/storage.yml
  db/schema.rb
  spec/support/capybara_driver_helper.rb
  terraform/azure/.terraform-docs.yml
  terraform/azure/.terraform.lock.hcl
  terraform/azure/Readme.md
  terraform/azure/backend.tfvars.example
  terraform/azure/container-apps-hosting.tf
  terraform/azure/dns.tf
  terraform/azure/key-vault-tfvars.tf
  terraform/azure/locals.tf
  terraform/azure/main.tf
  terraform/azure/resource-group.tf
  terraform/azure/variables.tf
Labels: qa-skip

#1475 1378 - E&O Create Cases and Case List
  app/assets/stylesheets/components/supported/_towers-tabs.scss
  app/controllers/engagement/application_controller.rb
  app/controllers/engagement/cases/previews_controller.rb
  app/controllers/engagement/cases_controller.rb
  app/controllers/support/concerns/filter_parameters.rb
  app/controllers/support/establishments_controller.rb
  app/forms/support/create_case_form.rb
  app/forms/support/create_case_form_schema.rb
  app/forms/support/engagement_case_filter_form.rb
  app/models/support/case.rb
  app/policies/cms_portal_policy.rb
  app/presenters/support/case_presenter.rb
  app/presenters/support/concerns/has_creator.rb
  app/services/support/create_case.rb
  app/services/support/filter_cases.rb
  app/views/engagement/cases/forms/_create_case_form.html.erb
  app/views/engagement/cases/index.html.erb
  app/views/engagement/cases/index/_detailed_case.html.erb
  app/views/engagement/cases/index/_detailed_cases.html.erb
  app/views/engagement/cases/index/_tab_all_cases.html.erb
  app/views/engagement/cases/new.html.erb
  app/views/engagement/cases/previews/new.html.erb
  app/views/engagement/cases/show.html.erb
  config/brakeman.ignore
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230627090123_add_creation_source_to_support_cases.rb
  db/migrate/20230629150515_add_created_by_to_cases.rb
  db/schema.rb
  spec/features/engagement/create_case_spec.rb
  spec/features/engagement/engagement_agent_login_spec.rb
  spec/models/support/case_spec.rb
  spec/support/capybara_driver_helper.rb
  spec/support/shared/engagement_agent.rb
Labels: qa-seeded, qa-deployed, qa-1

#1489 1529 - feat(cms): ability to sync frameworks with FaF
  .env.example
  .env.test
  .github/workflows/ci-full-pipeline.yml
  app/controllers/api/find_a_framework/frameworks_controller.rb
  app/controllers/support/management/sync_frameworks_controller.rb
  app/jobs/support/sync_frameworks_job.rb
  app/services/support/sync_frameworks.rb
  app/views/support/management/base/index.html.erb
  app/views/support/management/sync_frameworks/index.html.erb
  config/locales/en.yml
  config/routes.rb
  config/schedule.yml
  db/migrate/20230707133414_add_ref_to_support_frameworks.rb
  db/schema.rb
  lib/tasks/data_migrations.rake
  spec/factories/support/framework.rb
  spec/requests/self-serve/api/find_a_framework/webhook_upsert_framework_spec.rb
  spec/services/support/sync_frameworks_spec.rb
Labels: qa-skip
