Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-06, with the labels that each got.

#1432 fix(cms): Agent can send email tests reliability
  spec/features/support/emails/agent_can_send_new_emails_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1428 1261 - feat(rfh): add category selection
  app/controllers/framework_requests/categories_controller.rb
  app/controllers/framework_requests/messages_controller.rb
  app/controllers/framework_requests/procurement_amounts_controller.rb
  app/forms/framework_requests/category_form.rb
  app/models/framework_request.rb
  app/models/request_for_help_category.rb
  app/models/support/category.rb
  app/services/request_for_help/seed_categories.rb
  app/services/submit_framework_request.rb
  app/views/framework_requests/categories/_form.html.erb
  app/views/framework_requests/categories/edit.html.erb
  app/views/framework_requests/categories/index.html.erb
  app/views/framework_requests/categories/multiple.html.erb
  app/views/framework_requests/show.html.erb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/locales/validation/en.yml
  config/request_for_help/categories.yml
  config/routes.rb
  config/support/categories.yml
  db/migrate/20230523151800_create_request_for_help_categories.rb
  db/migrate/20230526130609_add_category_to_framework_requests.rb
  db/schema.rb
  lib/tasks/request_for_help.rake
  script/qa/seed
  spec/controllers/framework_requests/categories_controller_spec.rb
  spec/controllers/framework_requests/messages_controller_spec.rb
  spec/controllers/framework_requests/procurement_amounts_controller_spec.rb
  spec/factories/framework_requests.rb
  spec/factories/request_for_help_category.rb
  spec/features/self-serve/framework_requests/create_framework_request_dsi_spec.rb
  spec/features/self-serve/framework_requests/create_framework_request_guest_spec.rb
  spec/features/self-serve/framework_requests/edit_framework_request_guest_spec.rb
  spec/forms/framework_requests/category_form_spec.rb
  spec/models/request_for_help_category_spec.rb
  spec/models/self-serve/framework_request_spec.rb
  spec/services/request_for_help/seed_categories_spec.rb
  spec/services/self-serve/submit_framework_request_spec.rb
  spec/services/support/seed_categories_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1453 1413 - ci: add pg_trgm to postgres extensions
  terraform/app/variables.tf
Labels: qa-seeded, qa-deployed, qa-1

#1444 1388 - feat(cms): add email template attachments
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/components/supported/_template-edit.scss
  app/assets/stylesheets/components/supported/_template-manager.scss
  app/controllers/support/document_downloads_controller.rb
  app/controllers/support/management/email_templates_controller.rb
  app/forms/support/management/email_template_form.rb
  app/javascript/controllers/email_templates_edit_controller.js
  app/javascript/controllers/email_templates_edit_controller.test.js
  app/models/support/email_template.rb
  app/models/support/email_template_attachment.rb
  app/views/support/management/email_templates/form/_form.html.erb
  app/views/support/management/email_templates/template_manager/templates/_template.html.erb
  config/locales/en.yml
  config/routes.rb
  db/migrate/20230531145503_create_support_email_template_attachments.rb
  db/schema.rb
  spec/controllers/support/management/email_templates_controller_spec.rb
  spec/factories/support/email_template_attachment.rb
  spec/features/support/management/email_templates/admin_can_create_templates_spec.rb
  spec/features/support/management/email_templates/admin_can_edit_templates_spec.rb
  spec/forms/support/management/email_template_form_spec.rb
  spec/models/support/email_template_attachment_spec.rb
  spec/models/support/email_template_spec.rb
  spec/rails_helper.rb
  spec/support/sign_in_helpers.rb
Labels: qa-seeded, qa-6, qa-deployed
