Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-01, with the labels that each got.

#1245 Add missing ADRs
  doc/architecture/decisions/0025-use-i18n-tasks-to-manage-missing-translations.md
  doc/architecture/decisions/0026-use-semantic-logger-to-make-logs-more-readable.md
  doc/architecture/decisions/0027-use-flipper-to-manage-feature-flags.md
  doc/architecture/decisions/0028-use-clamav-to-scan-email-attachments.md
  doc/architecture/decisions/0029-use-tinymce-to-compose-rich-text-emails.md
  doc/architecture/decisions/0030-use-knapsack-to-run-tests-in-parallel.md
  doc/architecture/decisions/0031-use-crawlerdetect-to-ignore-bots-when-tracking-user-journeys.md
Labels: documentation, qa-skip

#1262 Option to add a case note when case is on hold
  app/controllers/support/interactions_controller.rb
  app/views/support/cases/_case_actions.html.erb
Labels: enhancement, qa-seeded, qa-deployed, qa-3

#1267 Pin docker buildx to fix OCI issue on CF
  .github/workflows/actions/build-docker-image/action.yml
Labels: qa-deployed, qa-3

#1268 Gems and yarn upated
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  app/presenters/support/messages/outlook_message_presenter.rb
  package.json
  yarn.lock
Labels: qa-seeded, qa-deployed, qa-3
