Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-05, with the labels that each got.

#1380 1382 - feat(cms): email templates
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/components/supported/_template-manager.scss
  app/controllers/application_controller.rb
  app/controllers/support/cases/message_threads_controller.rb
  app/controllers/support/management/email_template_groups_controller.rb
  app/controllers/support/management/email_templates_controller.rb
  app/forms/support/management/email_template_form.rb
  app/javascript/components/tinymce.js
  app/javascript/controllers/email_templates_edit_controller.js
  app/javascript/controllers/email_templates_edit_controller.test.js
  app/javascript/controllers/index.js
  app/models/support/email.rb
  app/models/support/email_template.rb
  app/models/support/email_template_group.rb
  app/presenters/support/email_template_presenter.rb
  app/services/support/emails/templates/parser.rb
  app/services/support/emails/templates/seed_groups.rb
  app/views/support/cases/messages/_reply_form_template.html.erb
  app/views/support/cases/messages/replies/_form.html.erb
  app/views/support/management/base/index.html.erb
  app/views/support/management/email_templates/edit.html.erb
  app/views/support/management/email_templates/form/_form.html.erb
  app/views/support/management/email_templates/form/_variable_warning.html.erb
  app/views/support/management/email_templates/index.html.erb
  app/views/support/management/email_templates/new.html.erb
  app/views/support/management/email_templates/template_manager/_filters.html.erb
  app/views/support/management/email_templates/template_manager/_template_manager.html.erb
  app/views/support/management/email_templates/template_manager/_templates.erb
  app/views/support/management/email_templates/template_manager/templates/_action_bar.html.erb
  app/views/support/management/email_templates/template_manager/templates/_template.html.erb
  app/views/support/management/email_templates/template_manager/templates/_template_tags.html.erb
  config/brakeman.ignore
  config/locales/en.yml
  config/locales/validation/support/en.yml
  config/routes.rb
  config/support/email_template_groups.yml
  db/migrate/20230420102034_create_support_email_template_groups.rb
  db/migrate/20230420102042_create_support_email_templates.rb
  db/migrate/20230420105021_add_support_email_template_to_support_emails.rb
  db/schema.rb
  lib/tasks/case_management.rake
  spec/factories/support/email.rb
  spec/factories/support/email_template.rb
  spec/factories/support/email_template_group.rb
  spec/features/support/management/email_templates/admin_can_create_templates_spec.rb
  spec/features/support/management/email_templates/admin_can_delete_templates_spec.rb
  spec/features/support/management/email_templates/admin_can_edit_templates_spec.rb
  spec/features/support/management/email_templates/admin_can_see_list_of_templates_spec.rb
  spec/forms/support/management/email_template_form_spec.rb
  spec/models/support/email_spec.rb
  spec/models/support/email_template_group_spec.rb
  spec/models/support/email_template_spec.rb
  spec/presenters/support/email_template_presenter_spec.rb
  spec/rails_helper.rb
  spec/services/support/emails/templates/parser_spec.rb
  spec/services/support/emails/templates/seed_groups_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1394 1283/case worker name visibility
  app/views/support/cases/index/_detailed_case.html.erb
  app/views/support/cases/index/_detailed_cases.html.erb
  app/views/support/cases/index/_simple_case.html.erb
  app/views/support/cases/index/_simple_cases.html.erb
  app/views/support/cases/index/_tab_all_cases.html.erb
  app/views/support/cases/index/_tab_my_cases.html.erb
  app/views/support/towers/show.html.erb
  spec/features/support/case_list_spec.rb
Labels: qa-seeded, qa-deployed, qa-4

#1395 refactor: Email service disclaimer.
  app/views/support/cases/messages/_reply_form_template.html.erb
Labels: qa-seeded, qa-deployed, qa-5

#1411 feat(cms): email template filters
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/components/_expander.scss
  app/assets/stylesheets/components/_tag-bar.scss
  app/assets/stylesheets/components/supported/_template-manager.scss
  app/controllers/support/management/email_templates_controller.rb
  app/forms/support/management/email_template_filter_form.rb
  app/helpers/support/expander_helper.rb
  app/helpers/support/tag_bar_helper.rb
  app/javascript/controllers/email_template_filters_controller.js
  app/javascript/controllers/email_templates_edit_controller.js
  app/javascript/controllers/expander_controller.js
  app/javascript/controllers/expander_controller.test.js
  app/javascript/controllers/index.js
  app/models/support/email_template.rb
  app/services/support/emails/templates/filter.rb
  app/views/support/helpers/_expander.html.erb
  app/views/support/helpers/_tag_bar.html.erb
  app/views/support/management/email_templates/template_manager/_filters.html.erb
  app/views/support/management/email_templates/template_manager/_templates.erb
  app/views/support/management/email_templates/template_manager/templates/_action_bar.html.erb
  app/views/support/management/email_templates/template_manager/templates/_summary.html.erb
  config/locales/en.yml
  spec/features/support/management/email_templates/admin_can_filter_templates_spec.rb
  spec/forms/support/management/email_template_filter_form_spec.rb
  spec/helpers/support/expander_helper_spec.rb
  spec/helpers/support/tag_bar_helper_spec.rb
  spec/services/support/emails/templates/filter_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1413 Retain layout for notes and logged contacts.
  app/assets/stylesheets/base/_frontend.scss
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/cases/message_threads/_message.erb
Labels: qa-seeded, qa-deployed, qa-1

#1414 Record interactions for additional changes
  app/controllers/support/cases/contact_details_controller.rb
  app/controllers/support/cases/organisations_controller.rb
  app/controllers/support/cases/summary_submissions_controller.rb
  app/cores/case_history/handle_case_state_changes.rb
  app/cores/case_management/assign_organisation_to_case.rb
  app/cores/case_management/update_case_contact_details.rb
  app/cores/case_management/update_case_summary_details.rb
  app/cores/case_management/update_case_support_level.rb
  app/forms/support/case_contact_details_form.rb
  app/forms/support/case_organisation_form.rb
  app/forms/support/case_summary_form.rb
  app/models/support/interaction.rb
  config/locales/en.yml
  spec/features/support/agent_can_change_case_summary_spec.rb
  spec/models/support/interaction_spec.rb
  spec/presenters/support/interaction_presenter_spec.rb
Labels: qa-seeded, qa-7, qa-deployed

#1420 Handle cases without a support level.
  app/views/support/cases/index/_detailed_case.html.erb
Labels: qa-seeded, qa-deployed, qa-3
