Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-03, with the labels that each got.

#1319 fix: remove validation on query text in cms
  app/forms/support/concerns/request_details_form_fields_schema.rb
  app/forms/support/create_case_form_schema.rb
Labels: qa-seeded, qa-deployed, qa-5

#1324 fix(cms): dynamic messages frame
  app/controllers/support/cases/message_threads_controller.rb
  app/views/support/cases/show.html.erb
  spec/controllers/support/cases/message_threads_controller_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1325 fix(cms): fix case value presentation
  app/presenters/support/case_presenter.rb
  app/views/support/cases/show/_case_details.html.erb
  app/views/support/cases/summary_submissions/edit.html.erb
  spec/presenters/support/case_presenter_spec.rb
Labels: qa-seeded, qa-deployed, qa-3

#1323 chore(cms): change date formats
  app/helpers/date_helper.rb
  app/presenters/support/contract_presenter.rb
  app/presenters/support/message_presenter.rb
  app/views/support/cases/case_history/_interaction.html.erb
  app/views/support/cases/index/_detailed_case.html.erb
  app/views/support/cases/index/_simple_case.html.erb
  app/views/support/cases/index/_simple_cases.html.erb
  app/views/support/cases/message_threads/_logged_contact_thread.html.erb
  app/views/support/cases/message_threads/_templated_message_thread.html.erb
  app/views/support/cases/message_threads/_thread.html.erb
  app/views/support/cases/searches/_result.html.erb
  app/views/support/cases/show/_case_attachments.html.erb
  app/views/support/cases/show/_case_details.html.erb
  app/views/support/cases/show/_case_history.html.erb
  config/locales/en.yml
  spec/features/support/case_list_spec.rb
  spec/features/support/interactions/list_interactions_spec.rb
  spec/features/support/procurement_details/edit_existing_contract_spec.rb
  spec/features/support/procurement_details/edit_new_contract_spec.rb
  spec/helpers/self-serve/date_helper_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1328 879 - Show message contacts
  app/presenters/support/message_thread_presenter.rb
  app/presenters/support/messages/outlook_message_presenter.rb
  app/services/support/messages/outlook/message.rb
  app/services/support/messages/outlook/send_reply_to_email.rb
  app/services/support/messages/outlook/synchronisation/steps/persist_email.rb
  app/views/support/cases/message_threads/_recipient_table.html.erb
  app/views/support/cases/message_threads/_recipients.html.erb
  app/views/support/cases/message_threads/show.html.erb
  db/migrate/20230309165049_add_to_cc_bcc_recipients_to_support_emails.rb
  db/schema.rb
  lib/microsoft_graph/client.rb
  lib/tasks/data_migrations.rake
  spec/factories/support/email.rb
  spec/features/support/emails/agent_can_send_replies_spec.rb
  spec/presenters/support/messages/outlook_message_presenter_spec.rb
  spec/services/support/messages/outlook/send_reply_to_email_spec.rb
  spec/services/support/messages/outlook/synchronisation/steps/persist_email_spec.rb
Labels: qa-seeded, qa-deployed, qa-1
