Repository DFE-Digital/buy-for-your-school, pull requests merged in 2023-04, with the labels that each got.

#1339 feat(cms): auto filter of case attachments
  app/javascript/controllers/auto_filter_controller.js
  app/javascript/controllers/index.js
  app/views/support/cases/attachments/_filter.html.erb
Labels: qa-seeded, qa-6, qa-deployed

#1336 feat(cms): sortable tables
  app/assets/stylesheets/application.sass.scss
  app/assets/stylesheets/base/_misc.scss
  app/assets/stylesheets/components/supported/_table-sort-button.scss
  app/assets/stylesheets/components/supported/_towers-tabs.scss
  app/controllers/support/cases_controller.rb
  app/controllers/support/towers_controller.rb
  app/forms/support/case_filter_form.rb
  app/helpers/support/filter_helper.rb
  app/helpers/support/table_sort_helper.rb
  app/javascript/application.js
  app/javascript/components/sortable-th.js
  app/models/support/case.rb
  app/services/support/sort_cases.rb
  app/views/support/cases/forms/_simple_case_filters.html.erb
  app/views/support/cases/index/_detailed_case.html.erb
  app/views/support/cases/index/_detailed_cases.html.erb
  app/views/support/cases/index/_simple_case.html.erb
  app/views/support/cases/index/_simple_cases.html.erb
  app/views/support/cases/index/_tab_all_cases.html.erb
  app/views/support/cases/index/_tab_my_cases.html.erb
  app/views/support/cases/index/_tab_new_cases.html.erb
  app/views/support/helpers/_sortable_th.html.erb
  app/views/support/towers/show.html.erb
  config/brakeman.ignore
  config/locales/en.yml
  spec/features/support/case_list_spec.rb
  spec/features/support/filter_cases_spec.rb
  spec/forms/support/case_filter_form_spec.rb
  spec/helpers/support/filter_helper_spec.rb
  spec/helpers/support/table_sort_helper_spec.rb
  spec/models/support/case_spec.rb
  spec/services/support/sort_cases_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1361 1004 - feat: add referral routes
  app/controllers/referrals/referrals_controller.rb
  app/models/user_journey_step.rb
  config/application.rb
  config/routes.rb
  lib/middleware/user_journey_tracking.rb
  spec/controllers/referrals/referrals_controller_spec.rb
  spec/features/self-serve/auth/sign_out_spec.rb
Labels: qa-seeded, qa-deployed, qa-1

#1345 feat(cms): all-cases tab includes notes
  app/views/support/cases/index/_detailed_case.html.erb
  app/views/support/cases/index/_detailed_cases.html.erb
  app/views/support/cases/index/_tab_all_cases.html.erb
  spec/features/support/case_list_pagination_spec.rb
  spec/features/support/case_list_spec.rb
  spec/features/support/filter_cases_spec.rb
Labels: qa-seeded, qa-deployed, qa-4

#1338 feat(cms): add procurement value to create-a-case
  app/controllers/support/cases/previews_controller.rb
  app/controllers/support/cases_controller.rb
  app/forms/framework_requests/procurement_amount_form.rb
  app/forms/support/create_case_form.rb
  app/forms/support/create_case_form_schema.rb
  app/presenters/support/create_case_form_presenter.rb
  app/services/support/forms/validate_procurement_amount.rb
  app/views/support/cases/forms/_create_case_form.html.erb
  app/views/support/cases/previews/new.html.erb
  config/locales/en.yml
  config/locales/validation/support/en.yml
  spec/features/support/create_case_spec.rb
  spec/forms/framework_requests/procurement_amount_form_spec.rb
  spec/forms/support/create_case_form_schema_spec.rb
  spec/forms/support/create_case_form_spec.rb
  spec/presenters/support/create_case_form_presenter_spec.rb
  spec/services/support/forms/validate_procurement_amount_spec.rb
Labels: qa-seeded, qa-deployed, qa-5

#1368 1311 - feat(cms): exit survey embedded question
  .rubocop_todo.yml
  app/controllers/exit_survey/opt_in_controller.rb
  app/controllers/exit_survey/satisfaction_controller.rb
  app/jobs/support/send_exit_survey_job.rb
  app/models/exit_survey_response.rb
  app/services/emails/exit_survey.rb
  app/services/support/email_templates.rb
  db/migrate/20230418151950_add_sent_and_completed_dates_to_exit_survey_responses.rb
  db/schema.rb
  spec/features/support/case_resolution_spec.rb
  spec/models/exit_survey_response_spec.rb
  spec/services/self-serve/emails/exit_survey_spec.rb
Labels: qa-seeded, qa-deployed, qa-1
